### ISSUE TITLE
Bug Report Your First ^_^ :P On Death by any means client crash

### ISSUE THREAD

**Issue by Zerys2424** [websitenmaker12/Advanced-Genetics#1]
Since it doesn't crash properly and doesn't give an accurate crash/report / log I will describe what happens and how to recreate it. 

Setup forge
- Boot up a normal world
- Die in that world in any manner like falling or getting blown up by a creeper
- Game crashes straight away and window closes instantly. 

I am using this version of forge - 1.6.2-Forge9.10.1.871 
Or currently the latest version of forge for me. 

Good luck :)

Here is the crash reports anyway :D

http://pastebin.com/K7ptYkms

And this is the forge log one

http://pastebin.com/vs5GwNPb

Not as long but i believe i have highlighted what happens when i crash.

**Comment by websitenmaker12** [comment]
Probably you have an old version of advanced genetics because I fixed this bug in 1.5 I think.
