### ISSUE TITLE
Scraper not listed in the NEI for advancedgenetics-1.4.2-1.6

### ISSUE THREAD

**Issue by Gunner76th** [websitenmaker12/Advanced-Genetics#102]
I have checked and the Scraper is listed in the config file as Item ID 31743, however when you do an item lookup in the NEI, both by item name, and Item ID, you either come up with the Auto-Scraper (item name) or nothing at all (item ID). 

Also, if you use the recipe of 2 stone rods in bottom left and center center with an iron ingot in top right, you get the Pocket Computer  (Item ID 31999) instead of the expected Scraper. The correct recipe for the pocket computer is also listed in the NEI as Stone (item ID 1) in all Top, Left, and Right spots, with a golden Apple in center center, and a glass pane  in Bottom Center. Based on this information, it would appear that the recipe for the scraper somehow got linked to/overwriten to the pocket computer.

**Comment by websitenmaker12** [comment]
What you have is an ID-Conflict and not a bug.
