### ISSUE TITLE
crash with pipes and DNA Insulator

### ISSUE THREAD

**Issue by cstdenis** [websitenmaker12/Advanced-Genetics#104]
I think this is the same bug as #49, but with thermal expansion pipes instead of buildcraft pipes. #49 was closed saying it's a Buildcraft problem, but since it happens with thermalexpansion too that doesn't seem to be the case. 

The bug has caused the world to no longer load, here is the the crash report that happens when the level is loaded. 
## 

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/22/14 8:48 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 2
    at com.advGenetics.TileEntity.TileEntityDNAInsulator.func_70301_a(TileEntityDNAInsulator.java:40)
    at cofh.util.InventoryHelper.simulateInsertItemStackIntoInventory(InventoryHelper.java:163)
    at thermalexpansion.util.Utils.canAddToInventory(Utils.java:121)
    at thermalexpansion.part.conduit.item.ConduitItem.canRouteItem(ConduitItem.java:421)
    at thermalexpansion.part.conduit.item.TravelingItem.bounceItem(TravelingItem.java:153)
    at thermalexpansion.part.conduit.item.TravelingItem.tickForward(TravelingItem.java:71)
    at thermalexpansion.part.conduit.item.ConduitItem.tickItems(ConduitItem.java:211)
    at thermalexpansion.part.conduit.item.ConduitItem.doOutput(ConduitItem.java:104)
    at thermalexpansion.part.conduit.item.GridItem.doGridUpdate(GridItem.java:64)
    at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:75)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:622)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 542814032 bytes (517 MB) / 1017643008 bytes (970 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m
    AABB Pool Size: 2462 (137872 bytes; 0 MB) allocated, 2148 (120288 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 58
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 116 mods loaded, 116 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.9} [Not Enough Items](notenoughitems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.4} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](powercrystalscore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advancedgenetics{v1.4.1} [Advanced Genetics](advancedgenetics_v1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShipsMod{1.6.4 v1.4.5} [Archimedes' Ships](archimedesships.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Artifice{1.6.4R1.1.3} [Artifice](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|EE3{1.6.4R1.1.3} [Artifice Compat: EE3](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Forestry{1.6.4R1.1.3} [Artifice Compat: Forestry](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Vanilla{1.6.4R1.1.3} [Artifice Compat: Vanilla](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.6.4R2.7.6} [MineFactory Reloaded](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|MFR{1.6.4R1.1.3} [Artifice Compat: MFR](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Buildcraft{1.6.4R1.1.3} [Artifice Compat: Buildcraft](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|ForgeMicroblock{1.6.4R1.1.3} [Artifice Compat: ForgeMicroblock](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Thaumcraft{1.6.4R1.1.3} [Artifice Compat: Thaumcraft](artifice-1.1.3-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AutoBlocks{1.0.0} [AutoBlocks](autoblocks 1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Autoutils{1.0.1} [Autoutils](autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.8.0.43} [BetterStorage](betterstorage-1.6.4-0.8.0.45.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.5} [BiblioCraft](bibliocraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.1.14} [Natura](natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{1.2.1} [Biomes O' Plenty](biomesoplenty-universal-1.6.4-1.2.1.434.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsBoP{1.3} [BiblioWoods Biomes O'Plenty Edition](bibliowoods[biomesoplenty][v1.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsNatura{1.1} [BiblioWoods Natura Edition](bibliowoods[natura][v1.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{2.0.6} [Carpenter's Blocks](carpenter's blocks v2.0.6 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{2.0.0.2} [CoFH Core](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHLoot{2.0.0.2} [CoFH Loot](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHSocial{2.0.0.2} [CoFH Social](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{2.0.0.2} [CoFH World](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ConfigMod{v1.0} [Extended Mod Config](configmod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoroAI{v1.0} [CoroAI](coroai for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    darwin{0.2.3} [Darwin](darwin_0.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DragonMounts{r34} [Dragon Mounts](dragonmount_r35_mc1.6.x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnhancedCore{1.1.3} [EnhancedCore](enhancedcore_1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EP2{1.0.9} [EnhancedPortals 2](enhancedportals-2_1.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtendedRenderer{v1.0} [Extended Renderer](extendedrenderer for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FlansMod{4.1.1} [Flans Mod](flansmod-4.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FoodPlus{2.7-PRE} [§bFood Plus](food plus mod 2.7-PRE.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    633{${mod.version}} [Fossil/Archeology: Reported](fossilsarch-reported-v1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cfm{3.2.9.1} [§4MrCrayfish's Furniture Mod](furnituremodv3.2.9.1%281.6.4%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{2.0.11} [Galacticraft Core](galacticraft-1.6.4-2.0.11.978.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{2.0.11} [Galacticraft Mars](galacticraft-planets-1.6.4-2.0.11.978.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hamstermod{0.1} [Hamster Mod](hamsterrific[1.6.4]V2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hamstersforever{1.0} [Hamsters Forever](hamstersforever-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Hats{2.1.4} [Hats](hats2.1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{2.4.0} [iChunUtil](ichunutil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{57.2.0} [Immibis Core](immibis-core-57.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LiquidXP{57.1.2} [Liquid XP](liquid-xp-57.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.0} [MapWriter](mapwriter-2.0.16.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.6} [MFR Compat: Applied Energistics](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.6.4R2.7.6} [MFR Compat: Atum](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.6.4R2.7.6} [MFR Compat: BackTools](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.6} [MFR Compat: BuildCraft](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.6.4R2.7.6} [MFR Compat: Chococraft](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.6} [MFR Compat: ExtraBiomes](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.6.4R2.7.6} [MFR Compat: Forestry](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.6} [MFR Compat: Forestry (part 2)](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.6} [MFR Compat: ForgeMicroblock](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.6.4R2.7.6} [MFR Compat: IC2](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.6} [MFR Compat: Mystcraft](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.6.4R2.7.6} [MFR Compat: Pam's Mods](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.250} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.3.7.32} [ProjectRed](projectredbase-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.3.7.32} [ProjectRed-Exploration](projectredworld-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.6.4R2.7.6} [MFR Compat ProjectRed](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.6} [MFR Compat: Railcraft](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.6.4R2.7.6} [MFR Compat: RP2](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.6} [MFR Compat: Sufficient Biomes](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.6} [MFR Compat: Thaumcraft](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{3.0.0.2} [Thermal Expansion](thermalexpansion-3.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.6} [MFR Compat: Thermal Expansion](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.6} [MFR Compat: TwilightForest](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.6.4R2.7.6} [MFR Compat: Vanilla](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.6} [MFR Compat: XyCraft](minefactoryreloaded-2.7.6-448.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Minions{1.7.9b} [Minions](minions_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildMod{v1.0} [Build Mod](modbuild for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.7.1} [Morph](morphbeta-0.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    necromancy{1.4c} [Necromancy](necromancy-1.4c-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](neiplugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    notenoughkeys{0.0.4} [Not Enough Keys](notenoughkeys-1.6.4-0.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.4} [OpenMods](openmodslib-0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.2.7} [OpenBlocks](openblocks-1.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission](projectredintegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation](projectredmechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.1} [Waila](waila_1.5.1a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.6.X_1.5.4dev} [Tinkers' Construct](tconstruct_mc1.6.4_1.5.4d4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{4.3.7.32} [ProjectRed-Compatibility](projectredcompat-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.3.7.32} [ProjectRed-Integration](projectredintegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination](projectredlighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion](projectredmechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    QuantumCraft{1.1} [qCraft](qcraft1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RandomThings{1.9} [Random Things](random things v. 1.9 [MC 1.6.4].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SaintsPack{0.5} [Saintspack](saintspack.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    secretroomsmod{4.6.2} [The SecretRoomsMod](secretroomsmod-universal-1.6.4-4.6.2.319.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Statues{2.1.1} [Statues](statues-1.6.4-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Sync{2.1.1} [Sync](sync2.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TMechworks{19.d4b8fa0} [Tinkers' Mechworks](tmechworks_mc1.6.4_0.1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TrailMix{2.0.0} [TrailMix](trailmix2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    tropicraftmod{v5.1.6 for MC 1.6.4} [Tropicraft](tropicraft v5.1.6 Mod for MC v1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    volleyballmod{v5.1.6 for MC 1.6.4} [Volleyball](tropicraft v5.1.6 Mod for MC v1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waypoints{1.0.2} [Waypoints](waypoints-1.6.4-1.0.2fix.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AIBlock{v1.0} [AIBlock](weather v1.59 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WeatherMod{1.58} [Weather and Tornadoes](weather v1.59 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.16.3} [Witchery](witchery_0-16-3_164.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    worldofdinos{1.0} [World of Dinos](worldofdinos-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chisel{1.5.0} [Chisel](zchisel-1.6.4-1.5.0fix.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.250} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.250} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct Environment: Environment seems clean, however you are using a modpack; please report it to the pack author, not us!
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 830 (46480 bytes; 0 MB) allocated, 830 (46480 bytes; 0 MB) used
    Player Count: 1 / 8; [GCCorePlayerMP['cstdenis'/169, l='AttackBteam', x=-17.94, y=76.00, z=237.30]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by websitenmaker12** [comment]
Thats the same as #49. I am sure that this isn't my fault.
