### ISSUE TITLE
Network usage

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#107]
Version: advancedgenetics-1.5.3-1.7.2

I get multiple thousands of messages like this:
B#439]  [18:20:35] [Client thread/ERROR]: Messages for channel AdvGen_Network for side CLIENT were not processed by the embedded channel [com.advGenetics.Net.Packet.Packet3DNASync@53069c8e].
[B#439]   They have been dropped.
[B#439]  02 00 00 00 0a 00 00 00 00 00 00 c0                ............
[B#439]  Length: 12

(15 MByte of logfile within a couple of minutes)

Why is AdvGen so intensive in network usage?
There had been a fix before, due the crazy amount of traffic it used up. (100 MByte + / tick)

**Comment by websitenmaker12** [comment]
Oh no. That kind of bug already occured in AG for 1.6. I'll look what I can do.

**Comment by ghost** [comment]
Great to hear this, hopefully its much easier to fix (again) :+1:

**Comment by websitenmaker12** [comment]
Hopefully fixed in the next update. Wasn't able to reproduce the issue.
