### ISSUE TITLE
Swim in lava gene heals you when standing in lava

### ISSUE THREAD

**Issue by SixOneThree** [websitenmaker12/Advanced-Genetics#108]
Forge version: 10.12.1.1112
Advanced Genetics version: 1.5.3
Minecraft version: 1.7.2

If you have the swim in lava gene rather than it just preventing you from taking damage it reverses the damage (I think?) When I'm standing in lava it heals me by 3 hearts every time the lava should be damaging me, this can be abused with blood magic by standing in lava with a blood orb to fill up your life pool.

**Comment by websitenmaker12** [comment]
Fixed it.
