### ISSUE TITLE
Can't inject syringe.

### ISSUE THREAD

**Issue by JoeyLfan20** [websitenmaker12/Advanced-Genetics#11]
Whenever I try to inject syringe, it doesn't do anything.

**Comment by JoeyLfan20** [comment]
![2013-12-08_14 48 28](https://f.cloud.github.com/assets/6137781/1701362/135b07ce-6053-11e3-8862-df3770a79ea6.png)
 I'm holding down right button

**Comment by websitenmaker12** [comment]
You must put the syringe into the centrifuge.
