### ISSUE TITLE
mircoscope crash

### ISSUE THREAD

**Issue by joshuastutter** [websitenmaker12/Advanced-Genetics#110]
if I Put Anti genes in blood, It crashes (something about screen rendering)

**Comment by SixOneThree** [comment]
You should post the crash report, saying "it crashes something about screen rendering" is not enough, the crash report contains useful information for the mod author such as the file and even the line number.

**Comment by websitenmaker12** [comment]
Please post a crashlog. This isn't very useful as SixOneThree already said.
