### ISSUE TITLE
blood magic elemental scraper crash

### ISSUE THREAD

**Issue by braingkk** [websitenmaker12/Advanced-Genetics#111]
http://pastebin.com/Yp88TTF6

basically using a scraper on blood magic elementals causes a crash. simple fix is dont use scraper on it, but ofc there will always be stupid people on servers doing it anyway.

if i am reporting to the wrong mod author, let me know so i can forward this to the right person

**Comment by websitenmaker12** [comment]
Please report this bug to Blood Magic. This isn't my fault.
