### ISSUE TITLE
[1.7.2] Possible mis-use of netty in AdvGenetics?

### ISSUE THREAD

**Issue by sibomots** [websitenmaker12/Advanced-Genetics#113]
Warnings appearing in log:
Detected ongoing potential memory leak. 36300 packets have leaked. Top offenders
      AdvGen_Network : 32948

For example.

Version: advancedgenetics-1.5.4-1.7.2.jar
Server: cauldron-1.7.2-1.1126.04.35-server.jar

I'm wondering if you have been made aware of this?  If it's something to look at in advGenentics mod, and if I'm even submitting the issue in the right location..

Thanks for your time.

**Comment by websitenmaker12** [comment]
Yes you are right. I tought that I fixed it...

**Comment by sibomots** [comment]
OK.

I'll leave this in your hands then.

I'll help you test, if you wish.  Just let me know what works for you.

Thank you.

Sent from my Windows Phone

**Comment by websitenmaker12** [comment]
Closed because #112 reported the same but it is still not fixed.
