### ISSUE TITLE
Lot of Items Missing (Please Help)

### ISSUE THREAD

**Issue by XxFahimxX23** [websitenmaker12/Advanced-Genetics#12]
I looked at the forum and saw that i first need a scraper so i searched it up in NEI (Not Enough Items) and it wasn't there. I checked the others out and most important tools where gone. I do have other mods. Please help me. Thank you

**Comment by websitenmaker12** [comment]
This must be an Id-Conflict.

**Comment by InSimpleTermsJordan** [comment]
For those of you who also have this problem, DON'T set the IDs any higher than 31743 (for technical reasons, Forge can't use IDs above 31999 (Forge offsets IDs by 256 for whatever reason)). I suggest setting the highest IDs on the config of one of the conflicting mods to an ID LOWER than the lowest value on the same config before any edits. That's what worked for me.
