### ISSUE TITLE
Unstable FTB Pack

### ISSUE THREAD

**Issue by xXxXxXxXxXxXxXxXxXxXxXx** [websitenmaker12/Advanced-Genetics#120]
The DNA combiner will not combine the completed gene with a centrifuged syringe, instead it'll act like its combining the two and then it will just give me the syringe back as a filled un centrifuged syringe.

**Comment by websitenmaker12** [comment]
That isn't a bug. Recentrifuge the syringe and inject it. Than you will have the genes.
