### ISSUE TITLE
Crash when attempting to insert item into DNA Insulator

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#123]
When using another mod to attempt to insert an item (using item conduits from either Ender IO or Thermal Expansion) from the back of the insulator, the game crashes. This is the only block I have had issues with attempting to insert items into.

**Comment by websitenmaker12** [comment]
Can you please post the crashlog?

**Comment by ghost** [comment]
Ender IO: http://pastebin.com/hJbHXsuH

Thermal Expansion: http://pastebin.com/kqFWGiZU

**Comment by websitenmaker12** [comment]
Should be fixed in the next version.
