### ISSUE TITLE
Multiverse Problem 1.7.2

### ISSUE THREAD

**Issue by garfreak** [websitenmaker12/Advanced-Genetics#124]
Hello,
I have the following problem with AdvancedGenetics:
Everytime I go to another MV-World or another dimension, I loose my Abilities but I can recover them, when I take my blood, put it in the centrifuge and reinject it.
But this works global, if I go to a world wich has another InventoryGroup (via Multiverse Invenories), for example a Creativeworld, I can recover my genes too.
This is bad cause everyone could get the genes in creative and then go back to survival, reinject blood and have unfair-got abilities.

How can I fix this? Or is there allready any solution?
Thanks for Reading
GARFreak

**Comment by websitenmaker12** [comment]
I am not really sure what you mean but it seems that other worlds with "InventoryGroups" (?) are not overwriting the Entity NBT-Data. Do you agree with that?
