### ISSUE TITLE
DNA Breeder

### ISSUE THREAD

**Issue by trixonet** [websitenmaker12/Advanced-Genetics#125]
In 1.6.4 When shift--clicking a gene into another gene in the DNA Breeder it crashes your game

**Comment by ghost** [comment]
on the same lines of that when you place a Gene (None) Unuseable Cell in the right hand side of the dna breeder it crashes the game and if your on a server, it crashes the server

**Comment by websitenmaker12** [comment]
@SpongeCrafted Can you please post the crash-log?
@JustKraazy It was on purpose that I added the 'Unuseable Cell' disrictpion. You shouldn't use it.

**Comment by ghost** [comment]
Well you can still use it, is there anyway to disable that type of cell?

**Comment by websitenmaker12** [comment]
No, because otherwise I would disable all cells.

**Comment by trixonet** [comment]
I exceeded the pastebin so i copied from when i joined the server
Here's the link: http://pastebin.com/4mi5TVPU

**Comment by trixonet** [comment]
Here's the crashlog from the file that gets stored im not sure if its the same so 
Here's the link: http://pastebin.com/fniikrGx

**Comment by websitenmaker12** [comment]
Should be fixed in the next version.

**Comment by Sir-Will** [comment]
@websitenmaker12 what's the next version?

**Comment by websitenmaker12** [comment]
1.5.7

**Comment by ghost** [comment]
Is there any versions for 1.6.4 that fixes this bug? Rewrote*

**Comment by websitenmaker12** [comment]
No, not now

**Comment by Sir-Will** [comment]
Would be great if we get the fix for 1.6.4 too as it is a big issue.
