### ISSUE TITLE
magnifier issue

### ISSUE THREAD

**Issue by darkfang69** [websitenmaker12/Advanced-Genetics#128]
client 2.9.2.3 
1.6.4 sever yogscast complete pack 2.9.2.3
magnifier wont spawn in survial mode, it will on creative but if you switch but it despawns and so too does the Dna Analyser. please help fi this as realy want to play this mod thank you

**Comment by websitenmaker12** [comment]
I think that there is a ID-Conflict or something like this. I am may the wrong person to help you.
Maybe you should contact one of the creators of the pack.
