### ISSUE TITLE
Crash MC Forge 1.7.10 ; Place DNA Adder (?) Trying to do IC2

### ISSUE THREAD

**Issue by Ampflower** [websitenmaker12/Advanced-Genetics#130]
Crashing when placing a block, and tries to get IC2 API, causing world to be unload-able. V1.5.4. (Couldn't be tested any further, as downloads were not accessible)

**Comment by Ampflower** [comment]
Just to let you know, it was downloadable, just Adfly made it look like it wasn't. (Tested for 1.7.10 version, same thing. V1.5.6 still doesn't work. Removing IC2, and will see if problem still exist)

EDIT: It was the IC2 API. I removed it completely, and problem doesn't happen anymore.

**Comment by websitenmaker12** [comment]
Fixed in the next version.
