### ISSUE TITLE
[1.6.4] bug and enchentment

### ISSUE THREAD

**Issue by Goten87** [websitenmaker12/Advanced-Genetics#131]
hello i just started using the mod today
right now i have Fly in the monster pack when i fly up high and go out of fly mode drop to the group its not giving me damage (donno if thats right in the 1.6.4 version)

also i will love to see the shift key for fly chance to Alt or someting else sins some tools need to use Shift like the Crescent hammer
its realy frustreating if its letting you fly down as well
so chance the fly down key to somthing else

furtere more i love the mod and hope to see even more added to it
maby a way to chance how you look
little like morph is doing but then only 1 type and no chance or you need to chance it in the Syringe
and you cannot add more them 1 type for it
so if u wanne be a creeper add the creeper and no other skinn can be added

**Comment by websitenmaker12** [comment]
1. That is on purpose because you are in some sort of Gamemode 1.
2. When you press Shift+Space at the same time you can hover in air.
3. Development is shifted to AG2. I will not add new complicated content like that to AG.
