### ISSUE TITLE
advancedgenetics-1.5.6-1.7.10 Memory Leak Issue

### ISSUE THREAD

**Issue by djoveryde** [websitenmaker12/Advanced-Genetics#133]
Im using advancedgenetics-1.5.6-1.7.10 with Cauldron-1.7.10-1.1207.01.187-server.
Every few minutes i get the following error with different packets lost but same offenders

[22:30:27 ERROR]: Detected ongoing potential memory leak. 200 packets have leake
d. Top offenders
[22:30:27 ERROR]:        AdvGen_Network : 114
[22:30:27 ERROR]:        CFM : 86
[22:30:40 INFO]: Created Retrogen database for dimension -1

**Comment by neythan99** [comment]
que vacan

**Comment by websitenmaker12** [comment]
Can you give me a short overview of what you have done with Advanced Genetics?

**Comment by Redlotus99** [comment]
I can confirm this issue when doing just about anything with Advanced Genetics.

**Comment by websitenmaker12** [comment]
Closed because #145 is the same.
