### ISSUE TITLE
ClientThread/WARN Illegal prefix

### ISSUE THREAD

**Issue by Painstouch** [websitenmaker12/Advanced-Genetics#137]
https://gist.github.com/Painstouch/f844df139b361afdf9ee

Having this console spam is quite bothersome and would be nice if it could be resolved.

**Comment by websitenmaker12** [comment]
This problem was reported before but if I fix it, all AG users will loose all their blocks and items.

**Comment by Painstouch** [comment]
Despite all that, could the error be suppressed in any way or could there be a version specifically for users who do want to update and start anew? 

It's over 600 lines of "spam" in the console due to this.

Sorry for this bump.

**Comment by websitenmaker12** [comment]
I am afraid there is no solution.

**Comment by Painstouch** [comment]
Bummer :(

Thanks anyways!
