### ISSUE TITLE
More health gene prevents death

### ISSUE THREAD

**Issue by Doppelgangerous** [websitenmaker12/Advanced-Genetics#138]
With the Iron Golem gene when you die you drop your items but remain alive.

**Comment by DarkGuardsman** [comment]
List of mods installed http://pastebin.com/NHKcQerV

**Comment by websitenmaker12** [comment]
How did you got killed?

**Comment by DarkGuardsman** [comment]
Its been a while but we tested several deaths. Including fall damage, fire damage, player vs player, player vs mob, and machine related damage sources. I think this may be related to the onDeathEvent used by other mods like open blocks.

**Comment by websitenmaker12** [comment]
Did this problem occured again? Because I cannot reproduce it.

**Comment by DarkGuardsman** [comment]
Still happens with version 1.5.7 when in the modpack, sadly i don't have the time to do more testing. As i have to get a few builds out today. 

Here is the modpack i tested with http://www.technicpack.net/api/modpack/zerotheligers-pack

**Comment by mattymaats** [comment]
Hi Websitenmaker, 

I can confirm we have this issue as well on our modpack, what do you need to be able to get to the bottom of this one? It must be a mod conflict but due to DarkGuardsman not listing his mods or even the permissions for using the mods I can't tell what he has in the pack... 

Our modpack can be found here with all the mods listed - http://www.technicpack.net/modpack/details/nemalusion.428557

If you could take a look, let me know what you think the issue might be and I'll test it this end for you.

**Comment by websitenmaker12** [comment]
Maybe it is OpenBlocks? I am not really sure. It can be every mod that adds something when a player dies.

**Comment by DarkGuardsman** [comment]
@mattymaats Note its not my modpack so i don't mess with the permissions or configs. If the owner of the pack doesn't have permission that is on him. 

@websitenmaker12 Most likely your not canceling the event? That is the only thing i can think of that would cause an issue like this to pop up. As openblock's grave stone is still dropping during this issue meaning its receiving the onPlayerDeath event.

**Comment by mattymaats** [comment]
We don't use the OpenBlocks graves as we use the Gravestone mod for death inventories. 

The player does die and the message comes up in chat, their grave is also formed with their inventory inside of it but the player just goes back to full health standing there naked.

@DarkGuardsman, well thank you for posting on his behalf anyway but you should really inform him that he needs to fill out that information.

**Comment by DarkGuardsman** [comment]
@mattymaats OpenBlocks would be an example in this case but it does seem to be any mod that uses the onDeathEvent. However, the source is most likely advanced generics as the other mods should not see the event if it was consumed bring the player back to life.

@websitenmaker12 If upload the code to the repo i may be able to create a unit test to see whats wrong.

**Comment by websitenmaker12** [comment]
Fail. I found the issue. It is very silly .....

Code:
this.removeAttributesModifiersFromEntity(entity, attrMap);
entity.setHealth(entity.getMaxHealth());

It isn't a good idea to heal a entity that already died.

**Comment by websitenmaker12** [comment]
I'll post an update in the next days.
