### ISSUE TITLE
Advanced Genetics and Mekanism (and others) conflict without IC2 installed.

### ISSUE THREAD

**Issue by Serpardum** [websitenmaker12/Advanced-Genetics#139]
The issue is you are including the IC2 API in your jar.

If Advanced Genetics and Mekenism are both installed and IC2 isn't then Mekanism will crash.  See here for the bug tracker report from Mekanism: https://github.com/aidancbrady/Mekanism/issues/1742 all the way at the end.

When Mekanism is loaded it "sees" the API in your jar and things start loading as if IC2 was installed, which it isn't.  This issue also happens in one of the tinker construct mods also.

**Comment by websitenmaker12** [comment]
Yes. I've also noticed that but I won't be able to fix it in AG1. This issue is already fixed in AG2.
