### ISSUE TITLE
Heal Crystal Glitch

### ISSUE THREAD

**Issue by CoolJoey244** [websitenmaker12/Advanced-Genetics#14]
When i get the gene into me, and the heal-crystal in my inv, i get no regen, i am damageable.
Plz Help

**Comment by websitenmaker12** [comment]
when you added the gene and have the heal crystal in your inventory, the heal crystal absorbs the damage and
lose durability.

**Comment by CoolJoey244** [comment]
Oh,Yeah. I just figured it out b/c There were no vids on you tube about dat.

Date: Mon, 9 Dec 2013 07:00:02 -0800
