### ISSUE TITLE
Won't lose abilities upon death

### ISSUE THREAD

**Issue by chris75599** [websitenmaker12/Advanced-Genetics#140]
Me and My wife are playing the latest modsauce.(1.0.0.2)  I set up the machines and got a whole bunch of abilities.  Everything work like expected for me, but for my wife, things got a little wierd.  
She wouldn't lose her abilities when she died.  even stranger, anti gene won't work on her,(we had to get rid of night vision to  visit the deep dark).  I was able to use the antigene on myself no problem.
I gave her a copy of my blood, and it didn't update her abilities for her.  I made an extra copy of my blood for myself, and instead injected a  copy of her into me, Now, I can't lose abilites. with anti genes or my old blood. I've tried dyind with nothing on me, and getting rid of all beds, nothing.

**Comment by websitenmaker12** [comment]
Do you loose your inventory when you die?

**Comment by chris75599** [comment]
Yes, I just tested it.  Don't know if it helps or not, but the timer for nightvision II is at 19 secs. I currently have the following genes:
No-fall, Fly, NightVision, Resistence, +5 Hearts, Swim Lava, WaterBreathing

**Comment by websitenmaker12** [comment]
I guess that the problem isn't a cause of Advanced Genetics. Do you know whether it is possible that another mod saves some parts of the Player's Data when he dies?

**Comment by chris75599** [comment]
Gravestone maybe?   But I can't even use a anti-gene injection.  I was able to, but my wife couldn't. I used he blood on me and tried again, and then I wasn't able to.

**Comment by websitenmaker12** [comment]
That isn't a bug because Anit-Genes aren't saved in the DNA. They get destroied right after you inject them.
