### ISSUE TITLE
Ender IO Conduits Bug

### ISSUE THREAD

**Issue by GodNero** [websitenmaker12/Advanced-Genetics#143]
Minecraft: 1.7.10
Forge: 1208
Ender IO: 2.1.0.231
Advanced Genetics: 1.5.7
I can't seem to get any Ender IO conduits to connect to Advanced Genetics mcahines.

This issue happens SSP/SMP, Mekanisim and IC2 power conduit/cable however seems to be working fine.

GodNero - RR3 Pack Dev

Issue on Ender IO GitHub - https://github.com/CrazyPants/EnderIO/issues/1135

**Comment by websitenmaker12** [comment]
That's not a bug. Advanced Genetics doesn't support RF at the moment.

**Comment by GodNero** [comment]
Ok thanks, for the heads up.
