### ISSUE TITLE
jump boost and resistance not working

### ISSUE THREAD

**Issue by ignitor123** [websitenmaker12/Advanced-Genetics#144]
when I use the jump boost and resistance gene on me nothing happened.For resistance it did say the status but it is not working and i also followed the steps on how to use the mod .I am using 1.7.10

**Comment by ignitor123** [comment]
Can someone please answer?

**Comment by websitenmaker12** [comment]
Are you sure that these genes are in your DNA?

**Comment by ignitor123** [comment]
yes

**Comment by ignitor123** [comment]
I tried it many times but it did not work.I even tried reinstalling the game

**Comment by ignitor123** [comment]
I also used the microscope to ensure that I have the genes in my DNA

**Comment by websitenmaker12** [comment]
That is interesting, do the potion effects show up in your inventory?

**Comment by ignitor123** [comment]
Only for resistance but it did not work.I also  tried downgrading to the 1.6.4 version and the jump boost work but the resistance still did not work.

**Comment by websitenmaker12** [comment]
Ok, how long do you have the resistance potion?

**Comment by ignitor123** [comment]
For resistance it said 0:00.jump boost ,nothing.i am still now using the jump boost and resistance gene but did not work.the other genes appears to be working properly for me though.

**Comment by websitenmaker12** [comment]
Ok, I'll try to fix this.

**Comment by ignitor123** [comment]
Thanks i will be waiting for it
