### ISSUE TITLE
DNA Breeder -  Server crash 1.7.10-1.5.7 

### ISSUE THREAD

**Issue by TorchedCore** [websitenmaker12/Advanced-Genetics#147]
Full crash report in the pastebin

http://pastebin.com/BfJhLciU

The breeder caused the following server crash whenever the chunk was loaded (as this base had a world anchor, that was on server startup)

Not too sure on the specifics of what the machine was processing, the player was unsure.

Let me know if you need more detail.

**Comment by mattymaats** [comment]
This was an issue on 1.6.4 as well, from what I've seen it looks like it's due to the gene being bred corrupting and turning into a generic gene with no attributes.

**Comment by Banandana** [comment]
+1, issue occurred for me as well.

**Comment by websitenmaker12** [comment]
@Banandana What did you put into the Breeder?

**Comment by Banandana** [comment]
I don't know, but it just seemed to have happened.

**Comment by R0B0B3AR** [comment]
I got the same thing happen. It crashed my server. All I did was automate it with the ejector upgrades and left it running with bat scales. I would really love to have this mod back on the server.

**Comment by mattymaats** [comment]
Ok I've managed to reproduce this to work out what's causing it, at least some of the time. If you start processing the genes and the chunk is unloaded such as a player leaving the area or the server restarting it seems to corrupt the gene that's being processed. This can be reproduced in the DNA Breeder & DNA Combiner.

**Comment by greyjester** [comment]
ok here i have a crash report this is happening to us also its due to a block entity from the dna breeder i have a crash report and heres the link 

http://pastebin.com/WXWYbnUp

 this is happening to me as well
