### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by klangg** [websitenmaker12/Advanced-Genetics#159]
It looks like #145 / #133 is still popping up. Using advancedgenetics-1.7.10-1.5.8 and forge-1.7.10-10.13.2.1291-universal the console is reporting:
`[01:40:28] [Server thread/ERROR] [FML/]: Detected ongoing potential memory leak. 100 packets have leaked. Top offenders`
`[01:40:28] [Server thread/ERROR] [FML/]:         AdvGen_Network : 100`

Two players were online at the time. We have 13 players registered on the server. Let me know if I can provide anymore information that can help.

**Comment by tim-oster** [comment]
Was one of those players in the end?

**Comment by tim-oster** [comment]
How long was your server running and how often did you use the syringe on entities or yourself?
