### ISSUE TITLE
i can't shear any animals except a sheep.

### ISSUE THREAD

**Issue by hopcandy5** [websitenmaker12/Advanced-Genetics#16]
when i got the genetic wooly(from the sheep) i can't shear any other animals except a sheep.Am i doing something wrong?Please help.

**Comment by websitenmaker12** [comment]
Yes. When you add wooly tomyourself, it means that other players can shear you. When you extract blood from a mob and pur wooly on it and change the DNAof the mob, then you can shear it.

Obsi
