### ISSUE TITLE
Can't destroy any block even with pickaxe or with the hand.

### ISSUE THREAD

**Issue by Dennious** [websitenmaker12/Advanced-Genetics#160]
It happened when combining combine a gene to syringe and centrifuge it then I applied another gene to the syringe centrifuge it and then injected it. Then the bug happened.

Minecraft Version: 1.7.10 forge 10.13.3.1370
Single player. It happens with only Advanced Genetics mod and API installed.

**Comment by tim-oster** [comment]
Which gene did you inject?
