### ISSUE TITLE
Scraper recipe conflicting with Universal Electricity Water Cell

### ISSUE THREAD

**Issue by defakto** [websitenmaker12/Advanced-Genetics#17]
Running latest forge and the complete UE set all latest version.  The scraper fails to show in NEI and when attempting to craft, creates a Water Cell from the UE pack.

There is no Item ID conflict, scrap shows as 31743 in config, water cell is 31999

**Comment by websitenmaker12** [comment]
Sorry but this cannot be a bug of Advanced Genetics. It have to be an ID-Conflict because nobody elsereported this problem. Probably annother mod interferes with Advanced Genetics?
Obsi

**Comment by defakto** [comment]
Unfortunately, what we get is the spiral of solving nothing.

Both sides report it's another mod so at some point someone needs to step up and solve the issue.

**Comment by jalapeno777** [comment]
That is precisely an item ID conflict.  Forge mods sometimes have their IDs properly offset in the configs, others do not.

If it is not offset, the ID is actually 256 higher than what is in the config
31743 + 256 = 31999

Which means advanced genetics doesn't use offsetting for their config IDs.  You need to change one or the other to a non-used ID.
