### ISSUE TITLE
Swim in Lava Gene not Working 1.7

### ISSUE THREAD

**Issue by tyler2k15** [websitenmaker12/Advanced-Genetics#170]
Hello.

I recently got the Swim in lava gene, but it is not working. I am still dying whenever I go in lava. it shows up when I do /gene list

**Comment by tim-oster** [comment]
Do you have other mods installed?

**Comment by tyler2k15** [comment]
Using the revenge of the C Team mod pack. I believe it may be due to thermos (fork of kCauldron) and is supposed to have been fixed in 

https://github.com/TCPR/Thermos/commit/acd96ce220ef12fb265d0999ee3893be2ded789d

**Comment by MJRLegends** [comment]
im getting the same issue with kCauldron it self
