### ISSUE TITLE
More hearts

### ISSUE THREAD

**Issue by lethend** [websitenmaker12/Advanced-Genetics#18]
ether this ability "More hearts: adds 5 more hearts" is not working or it is not working with the blood magic mod. just letting u know.

thanks

**Comment by blaisen** [comment]
They work fine in conjunction for me, though occasionally the extra hearts refuse to display. Make sure you re-inject yourself with the serum if you've died; from what I've seen (not sure if this is a bug or a feature) you lose all of the genes in your DNA when you perish.

**Comment by websitenmaker12** [comment]
It is a feature.
