### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by fadi626** [websitenmaker12/Advanced-Genetics#19]
i just installed the mod everything is working great other than the scalpel is not in the game even in nei on creative mode so i cant really play this mod on survival

**Comment by websitenmaker12** [comment]
It is called 'Scraper'. Does this help you?

**Comment by fadi626** [comment]
no but i did try removing some other mods and i found out is was a problem with some id but thanks anyway

**Comment by websitenmaker12** [comment]
No problem.
