### ISSUE TITLE
Crash in the Remover

### ISSUE THREAD

**Issue by Tyro533** [websitenmaker12/Advanced-Genetics#2]
I put a syringe with blood having the anti-falldmg gene (was in the centrifuge already) and an antigene into the Remover and it crashed my mc

Bugreport: 
---- Minecraft Crash Report ----
// Why did you do that?

Time: 28.09.13 15:54
Description: Rendering screen

java.lang.NullPointerException
    at com.advGenetics.Items.ItemSyringe.func_77624_a(ItemSyringe.java:122)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74184_a(GuiContainer.java:226)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:202)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:944)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.advGenetics.Items.ItemSyringe.func_77624_a(ItemSyringe.java:122)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74184_a(GuiContainer.java:226)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:202)

-- Screen render details --
Details:
    Screen name: com.advGenetics.GUI.Client.GuiDNARemover
    Mouse location: Scaled: (265, 82). Absolute: (530, 314)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Tyro533'/424, l='MpServer', x=274,76, y=66,62, z=162,87]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (52,64,256), Chunk: (at 4,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 18019 game time, 18019 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 96 total; [EntityZombie['Zombie'/544, l='MpServer', x=353,72, y=22,00, z=97,25], EntityBat['Bat'/387, l='MpServer', x=248,38, y=27,10, z=227,59], EntitySquid['Squid'/386, l='MpServer', x=245,50, y=56,34, z=178,50], EntitySquid['Squid'/385, l='MpServer', x=245,31, y=56,00, z=176,44], EntityCreeper['Creeper'/384, l='MpServer', x=249,50, y=53,00, z=160,38], EntityBat['Bat'/516, l='MpServer', x=337,63, y=24,00, z=90,04], EntitySkeleton['Skeleton'/517, l='MpServer', x=323,31, y=11,46, z=110,31], EntityZombie['Zombie'/518, l='MpServer', x=323,50, y=45,00, z=110,50], EntitySquid['Squid'/519, l='MpServer', x=325,44, y=61,00, z=182,50], EntityBat['Bat'/515, l='MpServer', x=322,52, y=23,56, z=84,45], EntityBat['Bat'/526, l='MpServer', x=339,75, y=57,80, z=89,75], EntityZombie['Zombie'/527, l='MpServer', x=343,50, y=80,00, z=84,50], EntitySquid['Squid'/520, l='MpServer', x=323,88, y=62,00, z=183,50], EntitySquid['Squid'/521, l='MpServer', x=329,28, y=61,06, z=180,78], EntityZombie['Zombie'/319, l='MpServer', x=221,63, y=41,00, z=160,94], EntityPig['Pig'/522, l='MpServer', x=335,66, y=68,00, z=191,47], EntityZombie['Zombie'/318, l='MpServer', x=218,67, y=28,14, z=150,50], EntityChicken['Chicken'/523, l='MpServer', x=333,50, y=68,00, z=235,50], EntityChicken['Chicken'/533, l='MpServer', x=338,50, y=69,00, z=236,50], EntityPig['Pig'/532, l='MpServer', x=340,50, y=67,00, z=192,50], EntityChicken['Chicken'/535, l='MpServer', x=338,41, y=69,00, z=227,59], EntityChicken['Chicken'/534, l='MpServer', x=337,78, y=69,00, z=234,31], EntitySkeleton['Skeleton'/529, l='MpServer', x=340,50, y=11,00, z=174,50], EntityBat['Bat'/528, l='MpServer', x=348,77, y=52,02, z=95,85], EntityPig['Pig'/531, l='MpServer', x=338,47, y=67,00, z=189,53], EntityChicken['Chicken'/295, l='MpServer', x=199,50, y=109,00, z=85,50], EntityPig['Pig'/530, l='MpServer', x=331,50, y=67,00, z=188,28], EntityChicken['Chicken'/297, l='MpServer', x=196,50, y=107,00, z=86,50], EntityChicken['Chicken'/298, l='MpServer', x=198,50, y=106,00, z=87,50], EntityChicken['Chicken'/302, l='MpServer', x=200,41, y=67,00, z=188,45], EntitySkeleton['Skeleton'/476, l='MpServer', x=281,50, y=26,00, z=240,50], EntityZombie['Zombie'/477, l='MpServer', x=283,09, y=26,00, z=242,31], EntityPig['Pig'/474, l='MpServer', x=287,50, y=64,00, z=237,50], EntityPig['Pig'/475, l='MpServer', x=284,50, y=64,00, z=235,50], EntityZombie['Zombie'/472, l='MpServer', x=275,06, y=41,00, z=149,41], EntityZombie['Zombie'/473, l='MpServer', x=280,50, y=30,00, z=227,50], EntityZombie['Zombie'/470, l='MpServer', x=283,31, y=14,00, z=146,53], EntityZombie['Zombie'/471, l='MpServer', x=275,31, y=42,20, z=146,69], EntityBat['Bat'/469, l='MpServer', x=276,60, y=45,82, z=110,67], EntityEnderman['Enderman'/326, l='MpServer', x=222,00, y=67,00, z=209,44], EntityZombie['Zombie'/463, l='MpServer', x=260,00, y=61,77, z=125,94], EntityPig['Pig'/327, l='MpServer', x=212,53, y=64,00, z=227,47], EntitySkeleton['Skeleton'/462, l='MpServer', x=263,50, y=26,01, z=110,31], EntityItem['item.item.egg'/324, l='MpServer', x=218,19, y=63,13, z=192,88], EntitySpider['Spider'/461, l='MpServer', x=265,28, y=14,00, z=127,47], EntitySkeleton['Skeleton'/460, l='MpServer', x=259,50, y=13,00, z=110,50], EntityEnderman['Enderman'/325, l='MpServer', x=215,66, y=64,00, z=203,91], EntityZombie['Zombie'/459, l='MpServer', x=264,70, y=12,02, z=107,30], EntitySquid['Squid'/322, l='MpServer', x=221,50, y=60,00, z=168,06], EntityChicken['Chicken'/323, l='MpServer', x=218,47, y=63,00, z=187,97], EntitySquid['Squid'/320, l='MpServer', x=217,91, y=61,00, z=179,47], EntitySquid['Squid'/321, l='MpServer', x=221,75, y=60,09, z=175,97], EntityPig['Pig'/330, l='MpServer', x=211,47, y=64,00, z=227,50], EntityPig['Pig'/328, l='MpServer', x=217,25, y=67,00, z=224,50], EntityPig['Pig'/329, l='MpServer', x=213,53, y=64,00, z=228,53], EntityZombie['Zombie'/375, l='MpServer', x=245,28, y=23,00, z=119,78], EntityZombie['Zombie'/504, l='MpServer', x=309,50, y=21,00, z=174,50], EntitySkeleton['Skeleton'/368, l='MpServer', x=231,50, y=62,00, z=229,50], EntitySquid['Squid'/505, l='MpServer', x=317,31, y=62,34, z=174,34], EntitySkeleton['Skeleton'/506, l='MpServer', x=306,50, y=67,00, z=218,50], EntityZombie['Zombie'/507, l='MpServer', x=316,03, y=34,00, z=226,53], EntitySkeleton['Skeleton'/381, l='MpServer', x=247,26, y=61,82, z=153,43], EntitySpider['Spider'/380, l='MpServer', x=255,22, y=67,00, z=148,81], EntityZombie['Zombie'/383, l='MpServer', x=249,59, y=53,00, z=164,50], EntityCreeper['Creeper'/382, l='MpServer', x=240,84, y=38,00, z=175,16], EntityCreeper['Creeper'/503, l='MpServer', x=310,50, y=21,00, z=112,50], EntitySkeleton['Skeleton'/377, l='MpServer', x=254,50, y=26,00, z=128,91], EntityOcelot['Ocelot'/496, l='MpServer', x=293,59, y=66,00, z=171,56], EntitySkeleton['Skeleton'/497, l='MpServer', x=296,56, y=67,00, z=219,99], EntitySpider['Spider'/376, l='MpServer', x=253,22, y=20,01, z=116,78], EntityPig['Pig'/498, l='MpServer', x=289,50, y=65,00, z=235,50], EntitySkeleton['Skeleton'/379, l='MpServer', x=247,50, y=62,16, z=146,53], EntityPig['Pig'/499, l='MpServer', x=289,50, y=64,00, z=234,50], EntityZombie['Zombie'/378, l='MpServer', x=241,50, y=43,00, z=155,50], EntityChicken['Chicken'/356, l='MpServer', x=237,44, y=66,00, z=104,41], EntitySquid['Squid'/493, l='MpServer', x=295,53, y=61,00, z=123,38], EntityChicken['Chicken'/357, l='MpServer', x=235,19, y=66,00, z=101,94], EntityBat['Bat'/492, l='MpServer', x=298,51, y=46,10, z=104,39], EntityItem['item.item.egg'/358, l='MpServer', x=235,88, y=65,13, z=104,06], EntityZombie['Zombie'/495, l='MpServer', x=290,16, y=13,00, z=151,31], EntityItem['item.item.egg'/359, l='MpServer', x=237,41, y=66,13, z=102,91], EntitySkeleton['Skeleton'/494, l='MpServer', x=289,50, y=48,00, z=142,91], EntityCreeper['Creeper'/489, l='MpServer', x=303,75, y=67,00, z=88,06], EntityCreeper['Creeper'/491, l='MpServer', x=299,50, y=22,00, z=106,50], EntityChicken['Chicken'/354, l='MpServer', x=235,50, y=65,00, z=102,50], EntityZombie['Zombie'/490, l='MpServer', x=303,13, y=21,00, z=104,53], EntityChicken['Chicken'/355, l='MpServer', x=232,50, y=67,00, z=99,50], EntityZombie['Zombie'/364, l='MpServer', x=229,13, y=63,00, z=225,13], EntitySpider['Spider'/365, l='MpServer', x=236,78, y=66,00, z=210,91], EntitySkeleton['Skeleton'/366, l='MpServer', x=224,31, y=31,00, z=235,50], EntityClientPlayerMP['Tyro533'/424, l='MpServer', x=274,76, y=66,62, z=162,87], EntityZombie['Zombie'/367, l='MpServer', x=229,50, y=32,00, z=238,50], EntityBat['Bat'/360, l='MpServer', x=241,75, y=29,73, z=132,47], EntityCreeper['Creeper'/361, l='MpServer', x=233,83, y=38,00, z=176,44], EntitySquid['Squid'/362, l='MpServer', x=224,75, y=59,13, z=175,78], EntitySpider['Spider'/363, l='MpServer', x=239,50, y=38,00, z=177,06]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2310)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:854)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 233754576 bytes (222 MB) / 526974976 bytes (502 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 13542 (758352 bytes; 0 MB) allocated, 1322 (74032 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v8.11 FML v6.4.2.881 Minecraft Forge 9.11.0.881 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.2.881} [Forge Mod Loader](minecraftforge-9.11.0.881.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.0.881} [Minecraft Forge](minecraftforge-9.11.0.881.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advancedgenetics{v1.5 BETA} [Advanced Genetics](advancedGenetics_vb1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.0.881
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 6900 Series GL version 4.2.11298 Compatibility Profile Context, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 5415 (303240 bytes; 0 MB) allocated, 1128 (63168 bytes; 0 MB) used

**Comment by websitenmaker12** [comment]
Thank you. In the next versoin this bug will be fixed!
