### ISSUE TITLE
Code in TickHandlerClientServerSync causes CME

### ISSUE THREAD

**Issue by OniBait** [websitenmaker12/Advanced-Genetics#22]
The code you have in your `TickHandlerClientServerSync` is causing a `ConcurrentModificationException` when you are removing the player via the hashmap instead of your iterator:

http://pastie.org/8598003#40

That is modifying the underlying connection and causing the `ConcurrentModificationException` -- Looks like you could easily fix it by changing that line to just:

`it.remove()`

Would also recommend you don't do that every tick, it seems awfully inefficient to be doing this check 20x/sec.

**Comment by websitenmaker12** [comment]
It is a bit scary that you have the code but anyway when do you get this error because I never got it?
Also don't worry. It doesn't update every tick.

**Comment by OniBait** [comment]
Not sure what the cause was (see the issue linked over from MCPC+) -- and we are pretty good and active at decompiling/deobfuscating Minecraft code.

On a side-note -- if this project was open source, we probably would've just sent you a Pull Request fixing it.
