### ISSUE TITLE
Heal Crystal Crash

### ISSUE THREAD

**Issue by eyamaz** [websitenmaker12/Advanced-Genetics#25]
the Heal Crystal is crashing in both Horizons/Monster test builds for updates (using AG 1.2) It seems to be because it is being used as a fuel in vanilla furnaces? this is causing the game to crash when looking up any recipes in NEI or by placing the Heal Crystal in the fuel slot in a furnace AND something than can be smelted in the smelting slot.

reverting back to 1.1 causes NEI to omit the heal crystal from its listings.

**Comment by websitenmaker12** [comment]
Ok. I am now working on it.
