### ISSUE TITLE
Abilities Vanish

### ISSUE THREAD

**Issue by solodad** [websitenmaker12/Advanced-Genetics#26]
After I close the client my abilities that I injected vanish, I am currently on 1.0.9 of the horizons pack if that helps any.

**Comment by websitenmaker12** [comment]
How did you close your client? Alt+F4 or did you save your world?

**Comment by solodad** [comment]
I am playing on my server, and just closed my client normally

**Comment by websitenmaker12** [comment]
Thats wired. Do you use an own modpack or only Advanced Genetics?

**Comment by solodad** [comment]
I use the Horizons modpack from FTB.

**Comment by websitenmaker12** [comment]
Ok. You are the first one who had this problem. Are you sure that this wasn't your fault?

**Comment by solodad** [comment]
Probably was. If I find a fix I will let you know :P
