### ISSUE TITLE
Milk?

### ISSUE THREAD

**Issue by zak1122** [websitenmaker12/Advanced-Genetics#28]
Not sure how this works but I've combined two into one Syringe, Eat Grass and Infinite Milk, the grass one works fine... However the Milk one does not seem to work, I've attempted everything besides using it on its own. Doing all the normal milk gathering actions on myself as well as other mobs, nothing seems to happen besides on the actual Cow... Help...?

**Comment by websitenmaker12** [comment]
When you add Milk to yourself, other players will be able to milk YOU. When you add the gene to a mob it will be milkable. I hope this can help you.

**Comment by zak1122** [comment]
Oh.... Ok, thanks for the clarification.
