### ISSUE TITLE
Collides with Mod "More Bows"

### ISSUE THREAD

**Issue by winsenkiller** [websitenmaker12/Advanced-Genetics#3]
The mod "more Bows" conflicts with yours. Recipes are messed up (see image) 
![beispiel 3](https://f.cloud.github.com/assets/5639280/1290079/649af41c-302b-11e3-83fa-8f02ce90875e.PNG)
![beispiel 2](https://f.cloud.github.com/assets/5639280/1290080/649c95ce-302b-11e3-8a58-e30c40e0eafe.PNG)
![beispiel 1](https://f.cloud.github.com/assets/5639280/1290081/64c0dace-302b-11e3-94a0-ca4bce0d2d04.PNG)

**Comment by ghost** [comment]
Goddamit this is an ID conflict. You have to be sure there are no ID overlaps.

**Comment by winsenkiller** [comment]
Ok ill try to use an ID fix mod I found. But when I'm right your mod is for 1.6.2 and i'm using 1.6.4  so can't use it for now. When it's updated for 1.6.4 I'll try it.

**Comment by ghost** [comment]
The title of our thread on the minecraft forums: "[1.6.4] [Forge] Advanced Genetics Mod"

**Comment by winsenkiller** [comment]
Oh srry haven't seen it. I'm not at home. Ok I'll try it when more bows is up to date.
