### ISSUE TITLE
Cells and organic drop glitch???

### ISSUE THREAD

**Issue by ChrisBAranda** [websitenmaker12/Advanced-Genetics#32]
Whenever I try to put the skin scales on the DNA Analyser, it only shows the organic drops. And when I click on the organic drops, it goes back to analyzing the skin scales. This not only relates to the DNA Analyser but it relates to all machines! It's a glitch! It's a good mod, but it has it glitches. Please help! Thanks!

P.S. I am using Minecraft 1.6.4

**Comment by websitenmaker12** [comment]
Are you sure that you have no ID-Conflicts and that you are using the latest version of AdvGen? This don't happen to me so are you sure that this isn't your fault?

**Comment by ChrisBAranda** [comment]
I am pretty sure. I have no ID-Conflicts, and I am using the latest version. I just downloaded last night.
