### ISSUE TITLE
Issue with vanilla mob mods and DNA

### ISSUE THREAD

**Issue by RODragon** [websitenmaker12/Advanced-Genetics#33]
From what I can tell, whenever you scrape a mob and it's a normal vanilla mob that has non basic DNA available, there is a chance that each skin scale will contain that DNA. Whenever a custom mob is scraped, each scale is always basic DNA. Lately I have been playing with both Advanced-Genetics and Father Toast's Special Mobs mod. The special mobs mod either changes or overwrites vanilla mobs in such a way that advanced-genetics no longer recognizes them as having non basic DNA available. As such DNA from mobs like this is no longer obtainable.

If possible, I'd suggest referencing the DNA tables by mob name, rather than ID (if that is what is currently done). For instance, one of the mobs added by special mobs is called a "Fire Creeper". Rather than trying to use the mob ID of the fire creeper to look up it's DNA potential, which in this case is only basic, check for key mob names. In this case comparing the mob name to "Creeper" would work. The same can be done with others, like using the keyword "Wither" for Wither skeletons. This method should also work with any new mobs that follow this naming pattern. For instance the "Mana Creeper" from Ars Magica.

**Comment by websitenmaker12** [comment]
That may work but this solution is not very professional and it would causes issues. AdvGen has an API which allowes Modders to work with AdvGen. So the author of the mob should use this API rather than override standart classes. Sorry, but it isn't my duty to override stuff because other mod-authors worked bad.
