### ISSUE TITLE
Blood withdrawl causing crashes in 1.1 of the mod

### ISSUE THREAD

**Issue by BlackAce21** [websitenmaker12/Advanced-Genetics#34]
not sure if this is fixed yet but in reference to a previous issue #21  (which I commented on) I will put it here as well.

I can answer this problem for you, we had this happen on our beta testing server for monster, we are running a public server for testing the new mod pack and upon inspection of the player.dat files involved we found that your code is copying the entire player.dat information (including all forge and bukkit location data in MCPC and i do mean EVERYTHING) and storing it inside that blood syringe item. This is not good as servers running both bukkit and forge will not be able to create more then a few blood syringes without maxing out their player.dat files with too much information for the server to process, it ends up crashing their client and they cant log back in until the syringes have been totally removed from their player files. (We have a lot of people highly versed in NBT editing) This could probably be fixed by having your code target only specific information from the player file and perhaps adding a way of targeting those specific details for the player so they have to draw blood for that specific trait only.

**Comment by websitenmaker12** [comment]
Oh. That makes a lot of things very clear... I thank you very much for this explination. I really thank you for that.
I will override the methods and in the next update of AdvGen it will be fixed.

Thank you very much!

**Comment by BlackAce21** [comment]
My pleasure :) glad I could help.
