### ISSUE TITLE
Unnamed Gene

### ISSUE THREAD

**Issue by Zenith-One** [websitenmaker12/Advanced-Genetics#35]
Crash to desktop bug when selecting an Unnamed Gene that I found in my splitter. Crash log can be found here: 

http://pastie.org/8634695

**Comment by websitenmaker12** [comment]
Which version of AdvGen do you use?

**Comment by Zenith-One** [comment]
The one in FTB Monster 1.0.5, which is 1.2.1

It seems to happen if I have a gene in the splitter and the chunk unloads either while it's processing or while it's got a gene in it. Either that or it's coming from a machine up the chain. I've got an auto-processing line leading up to the splitter, which is the manual one.  Hopper feeds scales into the analyzer and it auto-works itself up to the splitter.

Selecting that item in my inventory seems to crash me, as does that item being in the world.

**Comment by websitenmaker12** [comment]
Ok. That is wired. At this moment the only way to fix this is to break the machine and throw the item into lava without hovering it.

**Comment by Zenith-One** [comment]
Any insight as to what the cause is? e.g. if you do X, then you end up with Unknown Gene. Don't do X. 

For example, "If you leave your machines running and the chunk unloads, you'll get Unknown Genes and your client will crash. Don't leave things in your machines."
