### ISSUE TITLE
Teleport ability causing damage

### ISSUE THREAD

**Issue by Zenith-One** [websitenmaker12/Advanced-Genetics#37]
If this is intentional, disregard, but I recommend updating the wiki. =)

Using 1.2.1

**Comment by websitenmaker12** [comment]
Nice of you. But this is part of TeamDNA. Anyway, what would you like to update?

**Comment by Zenith-One** [comment]
The teleport ability is causing damage. If that's as intended, the wiki should be updated  to reflect that.

**Comment by websitenmaker12** [comment]
Ok. I will take a look at.

**Comment by Zenith-One** [comment]
Awesome, thanks! One note: I wouldn't mark issues as closed unless they're fixed or you decide not to fix them. Closed gives users the impression that one way or the other, you're done with it.

**Comment by websitenmaker12** [comment]
You are right. It is like an habit to always click 'Comment & Close'... ;)

**Comment by Zenith-One** [comment]
The Unknown Gene ticket got closed as well. =)
