### ISSUE TITLE
Crash related to AdvGen

### ISSUE THREAD

**Issue by iampyrex** [websitenmaker12/Advanced-Genetics#39]
Running Monster 1.0.3

Not sure how to duplicate, but server has crashed with same report 5 times in the last 45 minutes.

Crash Report
http://pastebin.com/3j28j1PE

pyRex

**Comment by websitenmaker12** [comment]
Yes, this bug is known and it should be fixed in version 1.2.1 but it needs time before FeedTheBeast can update it.
