### ISSUE TITLE
Abilities disapear after death

### ISSUE THREAD

**Issue by DyfeStrax** [websitenmaker12/Advanced-Genetics#40]
When I die all my abilities are gone. I have to re inject myself with them to get them back. I am playing in SMP but I have never tried it in SSP. Cant be sure whats causing this. At first I thought maybe it was the Save Inventory gene but its not. Hope you can find out why this happens. Thanks. Great mod by the way.

**Comment by websitenmaker12** [comment]
That isn't a bug. It is even a realistic feature.

**Comment by DyfeStrax** [comment]
Ok sorry for the confusion but it would be nice if you could make this a config file setting. I just find it a  little annoying. Thanks anyway

**Comment by Gemannihilator** [comment]
After you've injected the genes into your blood, you can extract your blood and re-inject it after you die to get all your abilities back
