### ISSUE TITLE
Cicken causing NoClassDefFoundError on pathfinding

### ISSUE THREAD

**Issue by Slind14** [websitenmaker12/Advanced-Genetics#43]
Stacktrace: http://pastebin.com/ccW76hai

ModList: https://feedthebeast.atlassian.net/wiki/display/PML/Monster+1.0.5

Caused by Microscope next to many chickens and other animals on small space.

**Comment by websitenmaker12** [comment]
This bug is fixed in the next version.

**Comment by Slind14** [comment]
good, which version number will it be ?

**Comment by websitenmaker12** [comment]
It will be version 1.3 which will maybe be relased in the next 3 days.
