### ISSUE TITLE
Unable to input cell to DNA Insulator (top,left and back)

### ISSUE THREAD

**Issue by blackbladr** [websitenmaker12/Advanced-Genetics#49]
I am playing your great mod with v1.4
## If input the item via the back, it crash =P

Input item to the second slot from right and the bottom is perfectly fine, output haven't test .

**Comment by websitenmaker12** [comment]
Please post a crashlog.

**Comment by blackbladr** [comment]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 14年2月17日 上午3:17
Description: Ticking tile entity

java.lang.ArrayIndexOutOfBoundsException: 2
    at com.advGenetics.TileEntity.TileEntityDNAInsulator.func_70301_a(TileEntityDNAInsulator.java:44)
    at buildcraft.core.inventory.InventoryIteratorSided$InvSlot.getStackInSlot(InventoryIteratorSided.java:56)
    at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:25)
    at buildcraft.core.inventory.Transactor.add(Transactor.java:15)
    at buildcraft.transport.PipeTransportItems.canReceivePipeObjects(PipeTransportItems.java:249)
    at buildcraft.transport.PipeTransportItems.getPossibleMovements(PipeTransportItems.java:216)
    at buildcraft.transport.PipeTransportItems.resolveDestination(PipeTransportItems.java:195)
    at buildcraft.transport.PipeTransportItems.injectItem(PipeTransportItems.java:112)
    at buildcraft.transport.PipeTransportItems.passToNextPipe(PipeTransportItems.java:312)
    at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:320)
    at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:299)
    at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:257)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:178)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.advGenetics.TileEntity.TileEntityDNAInsulator.func_70301_a(TileEntityDNAInsulator.java:44)
    at buildcraft.core.inventory.InventoryIteratorSided$InvSlot.getStackInSlot(InventoryIteratorSided.java:56)
    at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:25)
    at buildcraft.core.inventory.Transactor.add(Transactor.java:15)
    at buildcraft.transport.PipeTransportItems.canReceivePipeObjects(PipeTransportItems.java:249)
    at buildcraft.transport.PipeTransportItems.getPossibleMovements(PipeTransportItems.java:216)
    at buildcraft.transport.PipeTransportItems.resolveDestination(PipeTransportItems.java:195)
    at buildcraft.transport.PipeTransportItems.injectItem(PipeTransportItems.java:112)
    at buildcraft.transport.PipeTransportItems.passToNextPipe(PipeTransportItems.java:312)
    at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:320)
    at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:299)
    at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:257)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:178)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)

-- Tile entity being ticked --
Details:
    Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
    Block type: ID #1513 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (236,64,262), Chunk: (at 12,4,6 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #1513 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['Thomes'/252, l='New World', x=237.68, y=63.00, z=260.47]]
    Chunk stats: ServerChunkCache: 640 Drop: 0
    Level seed: -4650827215235839658
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (225,64,274), Chunk: (at 1,4,2 in 14,17; contains blocks 224,0,272 to 239,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 65511 game time, 65511 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 16859 (now: false), thunder time: 125173 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 449414176 bytes (428 MB) / 791674880 bytes (755 MB) up to 2330460160 bytes (2222 MB)
    JVM Flags: 1 total; -Xmx2500m
    AABB Pool Size: 3724 (208544 bytes; 0 MB) allocated, 3353 (187768 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 64
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 Optifine OptiFine_1.6.4_HD_C8 39 mods loaded, 39 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.7} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extendedEnchant{1.0.0} [Extended Enchanting](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.8} [Not Enough Items](NotEnoughItems 1.6.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DoggyTalents{v1.5.1a} [Doggy Talents]([1.6.4] Doggy Talents - v1.5.1a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AencEx{0.0.1} [AencEx]([1.6.x]Alpha MoreEnchantments V 8.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoreEnchantments{0.1.3} [More Player Enchantments]([1.6.x]Alpha MoreEnchantments V 8.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advancedgenetics{v1.4} [Advanced Genetics](advancedGenetics_v1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{2.0.0.2} [CoFH Core](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHLoot{2.0.0.2} [CoFH Loot](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHSocial{2.0.0.2} [CoFH Social](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{2.0.0.2} [CoFH World](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.16.5b} [Enchanting Plus](EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GunCus{1.6.4 BETA v2} [Gun Customization](GunCus 1.6.4 BETA v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GunCusExplosives{1.6.2 BETA v1.1} [Gun Customization Explosives](GunCus 1.6.4 BETA v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GunCusOfficialGuns{1.6.2 BETA v4} [Gun Customization Official Guns](GunCus 1.6.4 BETA v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.0} [MapWriter](mapwriter-2.0.16.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.12.01} [Mystcraft](mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SuperCraftingFrame{1.6.2.7} [Super Crafting Frame](SuperCraftingFrame-1.6.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.219} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{3.0.0.2} [Thermal Expansion](ThermalExpansion-3.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.6.X_1.5.2.1} [Tinkers' Construct](TConstruct_mc1.6.4_1.5.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.0.5b} [Thaumcraft](Thaumcraft4.0.5b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{2.1-74} [Thaumic Tinkerer](ThaumicTinkerer-2.1-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.219} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.219} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 5879 (329224 bytes; 0 MB) allocated, 5783 (323848 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Thomes'/252, l='New World', x=237.68, y=63.00, z=260.47]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by websitenmaker12** [comment]
I am sorry but this seems to be an issue of Buildcraft.
