### ISSUE TITLE
Crash caused by Transmutator

### ISSUE THREAD

**Issue by wurble00** [websitenmaker12/Advanced-Genetics#52]
I made a Transmutator machine, put some Organic Drops in it and as soon as I added the second part, an Empty Gene, my client crashed and my friend told me a min later the server crashed. I tried logging in again after this and both times it caused a crash. 
http://pastebin.com/ZBzfd1RZ

Issue was worked around by disabling Advanced Genetics mod on the server. 
Not my server btw, I just play on it.

**Comment by websitenmaker12** [comment]
Fixed it.

**Comment by wurble00** [comment]
Cheers for the prompt action
