### ISSUE TITLE
Warning in 1.6.4

### ISSUE THREAD

**Issue by theMiszcz** [websitenmaker12/Advanced-Genetics#56]
[SEVERE] [ForgeModLoader] Found anonymous item of class com.advGenetics.Items.ItemSyringe with ID 31993 owned by mod advancedgenetics, this item will NOT survive a 1.7 upgrade!
also this:
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnaextractor.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnabreeder.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnasplitter.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnaremover.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnatransmutator.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnacombiner.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnaautosplitter.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnaanalyser.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.dnaencoder.name.png
[SEVERE] [Minecraft-Client] Using missing texture, unable to load: advancedgenetics:textures/blocks/tile.centrifuge.name.png

**Comment by websitenmaker12** [comment]
Don't worry this isn't a bug or an issue.
