### ISSUE TITLE
stoneRod

### ISSUE THREAD

**Issue by theMiszcz** [websitenmaker12/Advanced-Genetics#57]
FML give me this output:
[FINE] [fml.ItemTracker] Adding item net.minecraft.item.ItemBlock(1012) owned by advancedgenetics
[INFO] [STDERR] 
[INFO] [STDERR] WARNING: 'stoneRod' is an invalid OreDictionary Name. The Name doesn't fit to the Type of Item and/or doesn't follow a proper OreDictionary Convention. If you are the Owner of the Mod who adds this Item, please do the following: 
[INFO] [STDERR] Put the 'Rod' in the beginning of the Name to get 'rodStone'
[INFO] [STDERR] Private Prefixes could also be a solution if the first Suggestion doesn't apply. In that case the suggestion for the name is 'advancedgenetics:stoneRod' don't forget to insert the ':' inbetween the Mod ID and OreDict Name, that is the most important part.
[INFO] [STDERR] If you are not the Owner then report it to the Owner of the Mod, which the Item belongs to.
[FINEST] [advancedgenetics] Sent event FMLInitializationEvent to mod advancedgenetics

**Comment by websitenmaker12** [comment]
Ok. That is interesting but it does work with Tinker's Construct so the name must be right...
