### ISSUE TITLE
Mod wont partially work

### ISSUE THREAD

**Issue by Aquadude** [websitenmaker12/Advanced-Genetics#60]
SO when I added this mod to my modpack that has IC2 ( I don't if its the problem) but when I click a mob with the scraper, it comes out as this upgrade every time.  I went into game mode one and in that category there wasn't any cells, genes, drops, whatever, just the machines and the tools.  I re-downloaded and installed but it was the same.  I don't know what to do.

**Comment by websitenmaker12** [comment]
That seems to be an ID-Conflict not a bug.
