### ISSUE TITLE
Packet overflow caused by 250-AGChannel

### ISSUE THREAD

**Issue by CoryManson** [websitenmaker12/Advanced-Genetics#66]
Good Evening,

I have been investigating problems with my players receiving packet overflow errors when they login to my server. Players with low bandwidth are immediately disconnected where players with good internet connections are fine but see their minecraft instance downloading a lot of data. The issue appears to get worse the longer the server is online (The worst we have seen is up to 3MB/s).

Running a packet analyser on the client, it is immediately apparent that clients are being spammed by Custom Packet 250-AGChannel which belongs to Advanced Genetics.

Unfortunately I am unsure of what causes the issue, the packet spam appears to ramp up the longer the server is online. The issue is worsened depending on how many players are actively using Advanced Genetics. (1 Server had very few and barely showed the issue whereas my second server had ~15 players all using Advanced Genetics and it was considerably worse)

Here is a pastebin of the packet data where you can see the spam: http://pastebin.com/NdjMypuu

I tested packet analysis in several parts of my world, my player has completely blank playerdata and has not done anything with advanced genetics, the packet spam affects all players that connect to the server regardless of their involvement. Not sure why all players need to receive the data in the first place =/

**Comment by websitenmaker12** [comment]
Which version of AdvGen do you use?

**Comment by CoryManson** [comment]
Currently using 1.4.1 in the ResonantRise modpack

**Comment by CoryManson** [comment]
Any luck with this?

**Comment by websitenmaker12** [comment]
No.

**Comment by JayWood** [comment]
I'm getting the same issue when I join on my server, disconnect.overflow.  Might I ask which program you used to get the output?  I tried using WireShark but I can't understand half of it and it looks nowhere near like your output.

**Comment by CoryManson** [comment]
The analysis was taken using an In-Game packet analyser mod made by Immibis.

He currently doesn't distribute it publicly. (I'm unsure on his view regarding redistribution)

**Comment by JayWood** [comment]
I'm not sure the exact cause and using Wireshark is like reading a second language.

With my issue, I'm not entirely sure it's Advanced Genetics because it only occurs at people's houses, including mine.  While at spawn, I have no problems.  It should also be noted that at my home I have not Adv. Genetics items in place, rather they're in a chest.  Which is why a program like you use would come in handy in finding out where this packet spam is coming from.

Current ModPack: FTB Monster v1.1.0

**Comment by CoryManson** [comment]
Feel free to get in touch with me at #OTEGamers on esper.net

**Comment by websitenmaker12** [comment]
Thanks. I will when I'll need it.

**Comment by websitenmaker12** [comment]
Was any of your players in the end?

**Comment by CoryManson** [comment]
When testing I had all my online players at spawn to see if the issue was local area or server wide.

No players were in the end.

**Comment by websitenmaker12** [comment]
I hope it is fixed in the new version. I rewrote the package system.
