### ISSUE TITLE
"/help" Syringe command crash

### ISSUE THREAD

**Issue by 61352151511** [websitenmaker12/Advanced-Genetics#69]
When you do /help followed by the number with whatever page the syringe command is on you get the following error

Advanced Genetics version: 1.5
MC Version: 1.7.2

![image](https://f.cloud.github.com/assets/2399411/2490480/31a243b4-b1ac-11e3-8e26-b6b9430c6dea.png)

**Comment by 61352151511** [comment]
Any news on if this is fixed or not? You kind of closed the issue without saying if it was fixed and there's no new version on the downloads page.

**Comment by websitenmaker12** [comment]
This will be fixed in the next update.

**Comment by 61352151511** [comment]
Ok, thanks :)
