### ISSUE TITLE
Hardcore Ender Dragon Crash

### ISSUE THREAD

**Issue by MinecraftBossKiller** [websitenmaker12/Advanced-Genetics#72]
I used a scraper on the Hardcore Ender Dragon and gave me the following crash:

---- Minecraft Crash Report ----
// Oops.

Time: 3/26/14 6:35 PM
Description: Unexpected error

java.lang.ClassCastException: chylex.hee.dragon.EntityDragon cannot be cast to net.minecraft.entity.boss.EntityDragon
    at com.advGenetics.Event.InteractEventHandler.onEntityInteract(InteractEventHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_101_InteractEventHandler_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1172)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:439)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1429)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1952)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:956)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:873)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.advGenetics.Event.InteractEventHandler.onEntityInteract(InteractEventHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_101_InteractEventHandler_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1172)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:439)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1429)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['coolbuilder65'/1835, l='MpServer', x=25.01, y=85.08, z=50.52]]
    Chunk stats: MultiplayerChunkCache: 321, 330
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 16211 game time, 7214 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 105 total; [EntityEnderman['Enderman'/732950, l='MpServer', x=-18.20, y=63.00, z=27.54], EntityEnderman['Enderman'/732949, l='MpServer', x=-20.69, y=63.00, z=29.09], EntityClientPlayerMP['coolbuilder65'/1835, l='MpServer', x=25.01, y=85.08, z=50.52], EntityEnderCrystal['entity.EnderCrystal.name'/730778, l='MpServer', x=-41.50, y=90.00, z=-22.50], EntityEnderman['Enderman'/731233, l='MpServer', x=12.24, y=58.00, z=17.57], EntityEnderman['Enderman'/732939, l='MpServer', x=-22.97, y=63.00, z=29.48], EntityEnderman['Enderman'/732936, l='MpServer', x=-23.87, y=63.00, z=29.66], EntityEnderman['Enderman'/731214, l='MpServer', x=4.20, y=58.00, z=25.23], EntityEnderman['Enderman'/731215, l='MpServer', x=24.80, y=60.00, z=51.58], EntityEnderCrystal['entity.EnderCrystal.name'/730806, l='MpServer', x=-53.50, y=84.00, z=-7.50], EntityEnderCrystal['entity.EnderCrystal.name'/730805, l='MpServer', x=-58.50, y=84.00, z=-7.50], EntityEnderman['Enderman'/731229, l='MpServer', x=72.69, y=48.00, z=17.00], EntityEnderman['Enderman'/731228, l='MpServer', x=45.22, y=60.00, z=-24.72], EntityEnderman['Enderman'/731230, l='MpServer', x=74.00, y=47.00, z=19.09], EntityEnderman['Enderman'/731227, l='MpServer', x=52.94, y=59.00, z=-17.50], EntityEnderCrystal['entity.EnderCrystal.name'/730792, l='MpServer', x=-61.50, y=66.00, z=-31.50], EntityEnderCrystal['entity.EnderCrystal.name'/730791, l='MpServer', x=-66.50, y=66.00, z=-31.50], EntityEnderman['Enderman'/731221, l='MpServer', x=21.69, y=60.00, z=49.66], EntityEnderman['Enderman'/731178, l='MpServer', x=81.47, y=42.00, z=19.00], EntityItem['item.item.string'/730840, l='MpServer', x=-13.06, y=100.13, z=46.19], EntityItem['item.item.string'/730842, l='MpServer', x=-13.88, y=100.13, z=49.53], EntityItem['item.item.string'/730843, l='MpServer', x=-13.88, y=87.13, z=50.72], EntityEnderman['Enderman'/731177, l='MpServer', x=35.50, y=57.00, z=68.06], EntityEnderman['Enderman'/731182, l='MpServer', x=-21.25, y=61.00, z=-13.38], EntityEnderman['Enderman'/731183, l='MpServer', x=-21.39, y=59.59, z=-10.20], EntityEnderman['Enderman'/731181, l='MpServer', x=57.94, y=26.00, z=46.53], EntityItem['item.item.string'/730847, l='MpServer', x=-14.09, y=102.13, z=47.44], EntityEnderman['Enderman'/731170, l='MpServer', x=57.84, y=45.35, z=28.31], EntityEnderman['Enderman'/731171, l='MpServer', x=54.78, y=40.00, z=33.63], EntityEnderman['Enderman'/731168, l='MpServer', x=50.00, y=49.00, z=12.97], EntityEnderman['Enderman'/731169, l='MpServer', x=61.50, y=40.00, z=33.50], EntityEnderCrystal['entity.EnderCrystal.name'/730837, l='MpServer', x=-6.50, y=75.00, z=-53.50], EntityEnderman['Enderman'/731172, l='MpServer', x=57.88, y=41.00, z=32.41], EntityEnderCrystal['entity.EnderCrystal.name'/730838, l='MpServer', x=-1.50, y=75.00, z=-53.50], EntityEnderman['Enderman'/731173, l='MpServer', x=66.50, y=29.00, z=39.50], EntityEnderCrystal['entity.EnderCrystal.name'/730839, l='MpServer', x=-3.50, y=67.00, z=19.50], EntityEnderman['Enderman'/731195, l='MpServer', x=63.31, y=57.00, z=3.69], EntityEnderman['Enderman'/731194, l='MpServer', x=77.31, y=48.00, z=13.91], EntityEnderman['Enderman'/731193, l='MpServer', x=29.16, y=58.00, z=84.84], EntityEnderman['Enderman'/731192, l='MpServer', x=32.72, y=58.00, z=86.25], EntityEnderman['Enderman'/731199, l='MpServer', x=36.66, y=54.00, z=58.50], EntityEnderman['Enderman'/731198, l='MpServer', x=58.69, y=57.00, z=13.22], EntityEnderman['Enderman'/731197, l='MpServer', x=62.22, y=47.00, z=15.66], EntityEnderman['Enderman'/731196, l='MpServer', x=56.09, y=58.00, z=-15.34], EntityEnderman['Enderman'/731187, l='MpServer', x=26.53, y=61.00, z=36.41], EntityEnderman['Enderman'/731186, l='MpServer', x=19.68, y=60.00, z=44.50], EntityEnderman['Enderman'/731185, l='MpServer', x=-8.66, y=60.00, z=-7.06], EntityEnderCrystal['entity.EnderCrystal.name'/730819, l='MpServer', x=-54.50, y=64.00, z=56.50], EntityEnderman['Enderman'/731184, l='MpServer', x=-15.97, y=60.00, z=-7.41], EntityEnderman['Enderman'/731191, l='MpServer', x=36.69, y=57.00, z=86.94], EntityEnderCrystal['entity.EnderCrystal.name'/730821, l='MpServer', x=-18.50, y=77.00, z=-24.50], EntityEnderCrystal['entity.EnderCrystal.name'/730820, l='MpServer', x=-54.50, y=64.00, z=61.50], EntityEnderman['Enderman'/731189, l='MpServer', x=30.38, y=60.00, z=43.91], EntityEnderman['Enderman'/731188, l='MpServer', x=31.50, y=60.00, z=38.50], EntityEnderCrystal['entity.EnderCrystal.name'/730822, l='MpServer', x=-15.50, y=78.00, z=61.50], EntityEnderman['Enderman'/731144, l='MpServer', x=31.13, y=57.00, z=66.22], EntityEnderCrystal['entity.EnderCrystal.name'/730875, l='MpServer', x=26.50, y=98.00, z=-47.50], EntityEnderman['Enderman'/731145, l='MpServer', x=17.43, y=61.00, z=24.23], EntityEnderman['Enderman'/731146, l='MpServer', x=18.53, y=60.00, z=22.59], EntityEnderman['Enderman'/731147, l='MpServer', x=15.50, y=60.00, z=2.50], EntityEnderCrystal['entity.EnderCrystal.name'/730878, l='MpServer', x=50.50, y=68.00, z=78.50], EntityEnderman['Enderman'/731148, l='MpServer', x=10.31, y=60.00, z=2.25], EntityEnderCrystal['entity.EnderCrystal.name'/730879, l='MpServer', x=56.50, y=90.00, z=-0.50], EntityEnderman['Enderman'/731149, l='MpServer', x=15.50, y=60.00, z=-7.03], EntityEnderCrystal['entity.EnderCrystal.name'/730876, l='MpServer', x=26.50, y=85.00, z=-25.50], EntityEnderman['Enderman'/731150, l='MpServer', x=13.50, y=60.00, z=1.63], EntityEnderCrystal['entity.EnderCrystal.name'/730877, l='MpServer', x=39.50, y=86.00, z=-1.50], EntityEnderman['Enderman'/731151, l='MpServer', x=37.03, y=54.00, z=63.44], EntityEnderCrystal['entity.EnderCrystal.name'/730866, l='MpServer', x=16.50, y=80.00, z=-16.50], EntityDragon['Ender Dragon'/730867, l='MpServer', x=32.20, y=84.38, z=50.09], EntityEnderCrystal['entity.EnderCrystal.name'/730864, l='MpServer', x=-2.50, y=114.00, z=-37.50], EntityEnderCrystal['entity.EnderCrystal.name'/730865, l='MpServer', x=-2.50, y=114.00, z=-32.50], EntityEnderman['Enderman'/731141, l='MpServer', x=32.53, y=58.00, z=59.41], EntityEnderman['Enderman'/731142, l='MpServer', x=34.75, y=58.00, z=57.31], EntityEnderCrystal['entity.EnderCrystal.name'/731954, l='MpServer', x=-99.50, y=68.00, z=13.50], EntityEnderman['Enderman'/731143, l='MpServer', x=32.06, y=57.00, z=66.69], EntityEnderman['Enderman'/731161, l='MpServer', x=58.38, y=57.00, z=4.97], EntityEnderman['Enderman'/731160, l='MpServer', x=57.94, y=46.00, z=17.41], EntityEnderman['Enderman'/731163, l='MpServer', x=56.13, y=58.00, z=3.69], EntityEnderman['Enderman'/731162, l='MpServer', x=64.22, y=57.00, z=5.03], EntityItem['item.item.string'/730851, l='MpServer', x=-13.88, y=99.13, z=52.75], EntityEnderman['Enderman'/731153, l='MpServer', x=39.50, y=54.00, z=64.50], EntityItem['item.item.string'/730850, l='MpServer', x=-14.13, y=102.13, z=50.88], EntityEnderman['Enderman'/731152, l='MpServer', x=35.91, y=54.00, z=62.00], EntityItem['item.item.string'/730849, l='MpServer', x=-12.84, y=103.13, z=48.81], EntityEnderman['Enderman'/731155, l='MpServer', x=47.59, y=39.00, z=36.56], EntityItem['item.item.string'/730848, l='MpServer', x=-13.13, y=87.13, z=47.28], EntityEnderman['Enderman'/731154, l='MpServer', x=45.09, y=55.00, z=67.38], EntityEnderman['Enderman'/731157, l='MpServer', x=19.36, y=60.00, z=18.80], EntityEnderman['Enderman'/731156, l='MpServer', x=6.58, y=59.00, z=4.09], EntityEnderCrystal['entity.EnderCrystal.name'/730853, l='MpServer', x=-10.50, y=114.00, z=51.50], EntityEnderman['Enderman'/731159, l='MpServer', x=11.31, y=60.00, z=3.13], EntityEnderCrystal['entity.EnderCrystal.name'/730852, l='MpServer', x=-10.50, y=114.00, z=46.50], EntityEnderman['Enderman'/731158, l='MpServer', x=4.78, y=59.00, z=5.63], EntityProjectileDragonFireball['entity.HardcoreEnderExpansion.ProjectileDragonFireball.name'/735681, l='MpServer', x=-1.97, y=80.66, z=43.25], EntityEnderman['Enderman'/731335, l='MpServer', x=4.53, y=58.00, z=79.00], EntityEnderman['Enderman'/731334, l='MpServer', x=4.16, y=58.00, z=81.38], EntityEnderman['Enderman'/731337, l='MpServer', x=3.34, y=58.00, z=80.41], EntityEnderman['Enderman'/731336, l='MpServer', x=-2.16, y=58.00, z=78.50], EntityEnderCrystal['entity.EnderCrystal.name'/731311, l='MpServer', x=-76.50, y=67.00, z=42.50], EntityEnderCrystal['entity.EnderCrystal.name'/731312, l='MpServer', x=-69.50, y=88.00, z=64.50], EntityEnderman['Enderman'/732893, l='MpServer', x=-17.08, y=60.00, z=-1.25], EntityEnderman['Enderman'/734322, l='MpServer', x=27.69, y=59.00, z=74.38], EntityEnderman['Enderman'/734323, l='MpServer', x=30.50, y=59.00, z=76.50], EntityEnderman['Enderman'/734321, l='MpServer', x=-41.50, y=62.00, z=-29.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:384)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2436)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:902)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 237937024 bytes (226 MB) / 708837376 bytes (676 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 9185 (514360 bytes; 0 MB) allocated, 9 (504 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.129.1047 Minecraft Forge 10.12.0.1047 Optifine OptiFine_1.7.2_HD_U_D1 51 mods loaded, 51 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.129.1047} [Forge Mod Loader](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.0.1047} [Minecraft Forge](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv0-alpha-64} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.0(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.0%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArmorStatusHUD{1.18(1.7.2)} [ArmorStatusHUD]([1.7.2]ArmorStatusHUD-client-1.18%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.1.0} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DirectionHUD{1.18(1.7.2)} [DirectionHUD]([1.7.2]DirectionHUD-client-1.18%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FloatingRuins{1.7.2.r02} [FloatingRuins]([1.7.2]FloatingRuins-universal-1.7.2.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DoggyTalents{v1.6.0a} [Doggy Talents]([1.7] Doggy Talents - v1.6.0a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advanceddispensers{1.1} [Advanced Dispensers Mod](AdvancedDispensers-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advancedgenetics{1.5} [Advanced Genetics](advancedgenetics-1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{5.0.4} [BuildCraft](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv0-alpha-64} [Applied Energistics 2](appliedenergistics2-rv0-alpha-64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BattleTowers{1.4.5} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.6.2} [BiblioCraft](BiblioCraft[1.6.2][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{5.0.4} [BC Builders](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{5.0.4} [BC Energy](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{5.0.4} [BC Factory](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{5.0.4} [BC Transport](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{5.0.4} [BC Silicon](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gud_cooler{1.0.1.1} [Coolers](cooler-1.7.2-1.1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SKC-Core{1.1.0.1} [SKC Core](SKC Core 1.1.0.1 - MC 1.7.2 - Forge %2810.12.0.1024%29 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SKC-CraftableHorseArmor{1.1.0.1} [Craftable Horse Armor](CraftableHorseArmor 1.1.0.1 - MC 1.7.2 - Forge %2810.12.0.1024%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftguide{1.5.2} [CraftGuide](CraftGuide-1.6.7.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomSpawner{3.2.0.dev.R1} [DrZhark's CustomSpawner](CustomMobSpawner 3.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DLDungeonsJBG{1.2.6} [Doomlike Dungeons](DoomlikeDungeons-1.2.6-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{6.2.0.dev.R1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DungeonPack{1.7.2-2.0} [DungeonPack](DungeonPack-1.7.2-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GrygrFlzr_GlowstoneWire{build 111} [Glowstone Wire](GSWireUniversal-1.7.x-srg-b111Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreEnderExpansion{1.5-BETA} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfernalMobs{1.4.8} [Infernal Mobs](InfernalMobs-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.11.717} [Iron Chest](ironchest-1.7.2-6.0.11.717-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.1.0c} [JABBA](Jabba-1.1.1_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    kwastimod{1.0.5} [Kwasti Bust Monsters](KwastiMod-1.7.2-1.0.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    reaper_lantern{1.44} [Lantern mod](Lantern1.44[1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    millenaire{5.2.0b2} [Millénaire](millenaire-5.2b2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modularfurnace{2.7.1} [Modular Furnace 2](modularfurnace-1.7.2-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modularpots{1.7.2.5} [Modular Flower Pots](ModularPots-1.7.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    necromancy{1.6.6} [Necromancy](Necromancy-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherDungeons{1.2.1} [Nether Dungeons](NetherDungeons-1.7.2-v-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    startools{1.0.0} [startools](NetherStar Tools 1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    newdungeons{1.7.2} [New Dungeons](NewDungeons-0.3%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidianBoat{v1.3.2} [Obsidian Boat](ObsidianBoat-1.7.2-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{12.4} [Ruins Spawning System](Ruins-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    securitycraft{v1.5-pre} [SecurityCraft](SecurityCraft_v1.5pre_for_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dg_slender{v3.3 1.7.2} [Slender Man](SlenderMan_3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wuppy29_slimedungeon{1.6.0} [Slime Dungeons](Slime Dungeons 1.6.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.4} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wildcaves3{0.4.3.6(1.7.2)} [Wild Caves 3](WildCaves3-0.4.3.6%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: alpha rv0-alpha-64 for Forge 10.12.0.1024
    AE2 Integration: IC2:OFF, BC:ON, MJ:ON, DSU:ON, FZ:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, FMP:OFF
    Launched Version: 1.7.2-Forge10.12.0.1047
    LWJGL: 2.9.0
    OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2202, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1779 (99624 bytes; 0 MB) allocated, 21 (1176 bytes; 0 MB) used
    Anisotropic Filtering: Off

If this is a problem with Hardcore Ender Dragon then I will report the bug on that mod.

**Comment by websitenmaker12** [comment]
This is because other mods patches the minecraft classes. I am not able to fix this at the moment.
But it would be good to know what mod do the patch.

**Comment by MinecraftBossKiller** [comment]
thanks for letting me know, I will check to see which mod it is.
