### ISSUE TITLE
Hardcore Ender Dragon Crash again, but only using Advanced genetics mod and hardcore ender expansion mod

### ISSUE THREAD

**Issue by MinecraftBossKiller** [websitenmaker12/Advanced-Genetics#74]
the issue with the hardcore ender dragon crashing when I use a scraper on it is still there, but this time I only used the advanced genetics mod and the hardcore ender expansion mod. Here is the crash to prove it.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/28/14 1:39 PM
Description: Unexpected error

java.lang.ClassCastException: chylex.hee.dragon.EntityDragon cannot be cast to net.minecraft.entity.boss.EntityDragon
    at com.advGenetics.Event.InteractEventHandler.onEntityInteract(InteractEventHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_33_InteractEventHandler_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1172)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:439)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1429)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1952)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:956)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:873)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.advGenetics.Event.InteractEventHandler.onEntityInteract(InteractEventHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_33_InteractEventHandler_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1172)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:439)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1429)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['coolbuilder65'/0, l='MpServer', x=-20.04, y=94.30, z=-8.52]]
    Chunk stats: MultiplayerChunkCache: 319, 319
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 16565 game time, 7214 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 165 total; [EntityItem['item.item.enderPearl'/785538, l='MpServer', x=-8.81, y=63.13, z=-12.44], EntityEnderman['Enderman'/779563, l='MpServer', x=-7.50, y=63.00, z=-17.69], EntityEnderman['Enderman'/779553, l='MpServer', x=-54.66, y=61.00, z=30.94], EntityEnderman['Enderman'/779555, l='MpServer', x=-36.91, y=62.00, z=-55.44], EntityEnderman['Enderman'/771924, l='MpServer', x=-70.25, y=61.00, z=-16.75], EntityEnderman['Enderman'/779569, l='MpServer', x=-5.63, y=62.00, z=-23.69], EntityEnderman['Enderman'/771921, l='MpServer', x=-57.00, y=62.00, z=-14.56], EntityEnderman['Enderman'/783422, l='MpServer', x=-53.41, y=61.00, z=31.22], EntityEnderman['Enderman'/783423, l='MpServer', x=-75.13, y=58.00, z=-36.50], EntityEnderman['Enderman'/783421, l='MpServer', x=-46.78, y=61.00, z=30.00], EntityEnderman['Enderman'/783418, l='MpServer', x=-53.59, y=61.00, z=30.34], EntityEnderman['Enderman'/783416, l='MpServer', x=-55.94, y=61.00, z=24.38], EntityEnderman['Enderman'/783414, l='MpServer', x=-46.97, y=62.00, z=26.59], EntityEnderman['Enderman'/783410, l='MpServer', x=12.06, y=59.00, z=67.41], EntityEnderman['Enderman'/783411, l='MpServer', x=6.88, y=59.00, z=66.44], EntityEnderman['Enderman'/783408, l='MpServer', x=18.84, y=60.00, z=62.91], EntityEnderman['Enderman'/783409, l='MpServer', x=11.28, y=59.00, z=64.22], EntityEnderman['Enderman'/783403, l='MpServer', x=-45.44, y=61.00, z=8.00], EntityEnderman['Enderman'/783401, l='MpServer', x=-58.94, y=61.00, z=23.63], EntityEnderman['Enderman'/783400, l='MpServer', x=-54.53, y=61.00, z=34.88], EntityEnderman['Enderman'/783399, l='MpServer', x=-59.44, y=61.00, z=26.03], EntityEnderman['Enderman'/783397, l='MpServer', x=-63.00, y=60.00, z=23.41], EntityEnderman['Enderman'/783395, l='MpServer', x=-57.00, y=61.00, z=31.50], EntityEnderman['Enderman'/786497, l='MpServer', x=-15.50, y=63.00, z=-1.50], EntityEnderman['Enderman'/786496, l='MpServer', x=-17.34, y=64.00, z=2.50], EntityEnderman['Enderman'/786499, l='MpServer', x=-26.01, y=63.00, z=1.63], EntityEnderman['Enderman'/786498, l='MpServer', x=-17.08, y=64.00, z=1.48], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/775929, l='MpServer', x=-38.50, y=89.00, z=10.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/775928, l='MpServer', x=-38.50, y=89.00, z=10.50], EntityXPOrb['Experience Orb'/747584, l='MpServer', x=-94.19, y=53.25, z=58.28], EntityItem['item.tile.whiteStone'/771971, l='MpServer', x=-46.81, y=62.13, z=-59.88], EntityItem['item.tile.whiteStone'/771970, l='MpServer', x=-31.88, y=62.13, z=-41.69], EntityItem['item.tile.whiteStone'/771973, l='MpServer', x=-45.41, y=62.13, z=-59.97], EntityItem['item.tile.whiteStone'/771975, l='MpServer', x=-47.13, y=62.13, z=-57.72], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/721491, l='MpServer', x=35.50, y=60.00, z=-47.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/721490, l='MpServer', x=35.50, y=60.00, z=-47.50], EntityItem['item.tile.whiteStone'/771979, l='MpServer', x=-47.66, y=62.13, z=-54.19], EntityItem['item.tile.whiteStone'/771981, l='MpServer', x=-49.16, y=62.13, z=-50.13], EntityItem['item.tile.whiteStone'/771980, l='MpServer', x=-48.34, y=62.13, z=-50.13], EntityItem['item.tile.whiteStone'/771982, l='MpServer', x=-46.13, y=62.13, z=-51.13], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/721492, l='MpServer', x=35.50, y=60.00, z=-47.50], EntityXPOrb['Experience Orb'/747583, l='MpServer', x=-97.29, y=55.25, z=59.22], EntityXPOrb['Experience Orb'/747582, l='MpServer', x=-94.44, y=53.25, z=58.72], EntityXPOrb['Experience Orb'/747581, l='MpServer', x=-97.59, y=53.25, z=59.34], EntityItem['item.tile.whiteStone'/771987, l='MpServer', x=-50.13, y=62.13, z=-45.03], EntityXPOrb['Experience Orb'/747580, l='MpServer', x=-94.09, y=53.25, z=60.16], EntityXPOrb['Experience Orb'/747579, l='MpServer', x=-94.00, y=53.25, z=58.66], EntityItem['item.tile.obsidian'/786457, l='MpServer', x=-11.16, y=91.13, z=-7.84], EntityItem['item.tile.whiteStone'/771989, l='MpServer', x=-51.13, y=62.13, z=-41.13], EntityItem['item.tile.whiteStone'/771994, l='MpServer', x=-49.06, y=62.13, z=-41.13], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/775850, l='MpServer', x=-38.50, y=89.00, z=10.50], EntityItem['item.tile.whiteStone'/771996, l='MpServer', x=-49.88, y=62.13, z=-40.13], EntityItem['item.tile.whiteStone'/771998, l='MpServer', x=-49.69, y=62.13, z=-43.81], EntityClientPlayerMP['coolbuilder65'/0, l='MpServer', x=-20.04, y=94.30, z=-8.52], EntityEnderman['Enderman'/744274, l='MpServer', x=-37.44, y=63.00, z=-18.03], EntityEnderman['Enderman'/786494, l='MpServer', x=-45.66, y=61.00, z=20.42], EntityEnderman['Enderman'/744269, l='MpServer', x=-40.16, y=64.00, z=-28.13], EntityEnderman['Enderman'/786492, l='MpServer', x=-43.50, y=61.00, z=19.63], EntityEnderman['Enderman'/786493, l='MpServer', x=-39.70, y=62.00, z=20.04], EntityEnderman['Enderman'/786490, l='MpServer', x=-49.50, y=61.00, z=22.50], EntityEnderman['Enderman'/786491, l='MpServer', x=-46.73, y=61.00, z=21.88], EntityEnderman['Enderman'/786489, l='MpServer', x=-45.88, y=61.00, z=21.29], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776036, l='MpServer', x=-39.50, y=87.00, z=7.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776033, l='MpServer', x=-39.50, y=86.00, z=8.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776060, l='MpServer', x=-38.50, y=87.00, z=8.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776061, l='MpServer', x=-38.50, y=87.00, z=8.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776058, l='MpServer', x=-38.50, y=86.00, z=8.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776059, l='MpServer', x=-38.50, y=86.00, z=8.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776053, l='MpServer', x=-38.50, y=87.00, z=8.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776050, l='MpServer', x=-38.50, y=86.00, z=8.50], EntityItem['item.tile.obsidian'/785800, l='MpServer', x=-9.53, y=91.13, z=-8.09], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776031, l='MpServer', x=-39.50, y=86.00, z=6.50], EntityEnderman['Enderman'/785907, l='MpServer', x=-37.97, y=62.00, z=44.47], EntityEnderman['Enderman'/785917, l='MpServer', x=-55.50, y=60.00, z=56.50], EntityEnderman['Enderman'/785916, l='MpServer', x=-51.84, y=59.00, z=58.56], EntityEnderman['Enderman'/785919, l='MpServer', x=-52.56, y=60.00, z=57.50], EntityEnderman['Enderman'/785889, l='MpServer', x=-64.50, y=61.00, z=12.50], EntityItem['item.tile.obsidian'/785758, l='MpServer', x=-9.50, y=91.13, z=-5.16], EntityItem['item.tile.obsidian'/785757, l='MpServer', x=-10.26, y=91.13, z=-3.13], EntityArrow['arrow'/718844, l='MpServer', x=41.97, y=58.28, z=-48.97], EntityItem['item.tile.whiteStone'/768441, l='MpServer', x=-22.53, y=62.13, z=-55.03], EntityItem['item.tile.whiteStone'/768440, l='MpServer', x=-23.84, y=62.13, z=-52.34], EntityItem['item.tile.whiteStone'/768442, l='MpServer', x=-24.22, y=62.13, z=-54.13], EntityItem['item.tile.obsidian'/785789, l='MpServer', x=-11.03, y=91.13, z=-6.47], EntityItem['item.tile.whiteStone'/768433, l='MpServer', x=-25.09, y=61.13, z=-70.78], EntityItem['item.tile.whiteStone'/768432, l='MpServer', x=-23.00, y=61.13, z=-71.75], EntityItem['item.tile.whiteStone'/768435, l='MpServer', x=-24.56, y=61.13, z=-67.22], EntityItem['item.tile.whiteStone'/768434, l='MpServer', x=-25.88, y=61.13, z=-70.53], EntityItem['item.tile.whiteStone'/768437, l='MpServer', x=-21.13, y=61.13, z=-68.16], EntityItem['item.tile.whiteStone'/768436, l='MpServer', x=-26.88, y=61.13, z=-71.84], EntityItem['item.tile.whiteStone'/768439, l='MpServer', x=-25.34, y=62.13, z=-54.34], EntityItem['item.tile.whiteStone'/768438, l='MpServer', x=-21.56, y=62.13, z=-55.28], EntityItem['item.tile.whiteStone'/768424, l='MpServer', x=-16.44, y=61.13, z=-72.88], EntityItem['item.item.enderPearl'/757428, l='MpServer', x=-32.22, y=62.13, z=10.19], EntityItem['item.tile.whiteStone'/768426, l='MpServer', x=-18.41, y=61.13, z=-71.41], EntityItem['item.tile.whiteStone'/768427, l='MpServer', x=-16.88, y=62.13, z=-64.88], EntityItem['item.tile.obsidian'/785770, l='MpServer', x=-8.84, y=91.13, z=-3.94], EntityItem['item.tile.whiteStone'/768428, l='MpServer', x=-16.31, y=62.13, z=-61.59], EntityItem['item.tile.whiteStone'/768430, l='MpServer', x=-17.44, y=62.13, z=-54.13], EntityItem['item.tile.whiteStone'/768431, l='MpServer', x=-17.72, y=62.13, z=-56.72], EntityItem['item.tile.obsidian'/785762, l='MpServer', x=-9.91, y=91.13, z=-4.47], EntityItem['item.tile.whiteStone'/768421, l='MpServer', x=-16.19, y=61.13, z=-70.72], EntityItem['item.tile.obsidian'/785764, l='MpServer', x=-8.78, y=91.13, z=-4.78], EntityItem['item.tile.whiteStone'/768423, l='MpServer', x=-16.53, y=61.13, z=-69.72], EntityXPOrb['Experience Orb'/785130, l='MpServer', x=104.13, y=57.25, z=29.03], EntityXPOrb['Experience Orb'/785129, l='MpServer', x=104.75, y=57.25, z=27.25], EntityItem['item.item.enderPearl'/776322, l='MpServer', x=-55.69, y=62.13, z=-11.84], EntityXPOrb['Experience Orb'/785113, l='MpServer', x=92.06, y=56.25, z=73.25], EntityXPOrb['Experience Orb'/785115, l='MpServer', x=94.38, y=57.25, z=72.81], EntityXPOrb['Experience Orb'/785114, l='MpServer', x=91.25, y=56.25, z=73.75], EntityXPOrb['Experience Orb'/785109, l='MpServer', x=91.75, y=56.25, z=74.75], EntityXPOrb['Experience Orb'/785108, l='MpServer', x=92.56, y=56.25, z=73.75], EntityXPOrb['Experience Orb'/785111, l='MpServer', x=92.06, y=57.25, z=71.94], EntityXPOrb['Experience Orb'/785110, l='MpServer', x=91.75, y=57.25, z=72.97], EntityXPOrb['Experience Orb'/785107, l='MpServer', x=91.66, y=56.25, z=74.75], EntityEnderman['Enderman'/785929, l='MpServer', x=3.44, y=64.00, z=4.44], EntityEnderman['Enderman'/785928, l='MpServer', x=17.44, y=64.00, z=9.59], EntityEnderman['Enderman'/785931, l='MpServer', x=13.16, y=64.00, z=6.34], EntityEnderman['Enderman'/785930, l='MpServer', x=16.38, y=64.00, z=11.84], EntityEnderman['Enderman'/785932, l='MpServer', x=15.50, y=64.00, z=8.50], EntityEnderman['Enderman'/785935, l='MpServer', x=9.03, y=64.00, z=-4.38], EntityEnderman['Enderman'/785934, l='MpServer', x=5.50, y=64.00, z=-0.28], EntityEnderman['Enderman'/785921, l='MpServer', x=-52.34, y=60.00, z=48.59], EntityEnderman['Enderman'/785923, l='MpServer', x=-50.84, y=60.00, z=56.66], EntityEnderman['Enderman'/785925, l='MpServer', x=8.50, y=64.00, z=0.50], EntityEnderman['Enderman'/785927, l='MpServer', x=12.63, y=64.00, z=4.34], EntityEnderman['Enderman'/785926, l='MpServer', x=12.00, y=64.00, z=2.59], EntityEnderman['Enderman'/785944, l='MpServer', x=-83.00, y=57.00, z=-19.50], EntityEnderman['Enderman'/785936, l='MpServer', x=-91.69, y=57.00, z=-13.13], EntityEnderman['Enderman'/785938, l='MpServer', x=-88.47, y=57.00, z=-15.00], EntityEnderman['Enderman'/785940, l='MpServer', x=-88.56, y=57.00, z=-15.94], EntityEnderman['Enderman'/785941, l='MpServer', x=-83.34, y=58.00, z=-12.06], EntityEnderman['Enderman'/785943, l='MpServer', x=-80.09, y=57.00, z=-22.63], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/775514, l='MpServer', x=-33.84, y=66.00, z=-16.97], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/722429, l='MpServer', x=43.38, y=60.00, z=-48.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/756856, l='MpServer', x=-14.34, y=67.00, z=10.69], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/775519, l='MpServer', x=-33.84, y=67.00, z=-16.97], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/756855, l='MpServer', x=-14.50, y=67.00, z=10.69], EntityEnderman['Enderman'/786323, l='MpServer', x=60.50, y=61.00, z=39.50], EntityEnderman['Enderman'/786320, l='MpServer', x=-2.78, y=60.00, z=56.72], EntityEnderman['Enderman'/786327, l='MpServer', x=57.56, y=61.00, z=46.44], EntityEnderman['Enderman'/786326, l='MpServer', x=59.50, y=61.00, z=44.50], EntityEnderman['Enderman'/786325, l='MpServer', x=60.66, y=60.00, z=41.50], EntityEnderman['Enderman'/786324, l='MpServer', x=54.94, y=61.00, z=35.44], EntityEnderman['Enderman'/786331, l='MpServer', x=55.00, y=61.00, z=42.41], EntityEnderman['Enderman'/786330, l='MpServer', x=55.72, y=61.00, z=44.16], EntityEnderman['Enderman'/786329, l='MpServer', x=58.50, y=61.00, z=43.50], EntityEnderman['Enderman'/786328, l='MpServer', x=57.56, y=61.00, z=48.00], EntityEnderman['Enderman'/786318, l='MpServer', x=-2.50, y=60.00, z=59.59], EntityEnderman['Enderman'/786319, l='MpServer', x=-3.34, y=60.00, z=59.00], EntityEnderman['Enderman'/786316, l='MpServer', x=-1.03, y=60.00, z=59.53], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/775484, l='MpServer', x=-40.81, y=66.00, z=-17.19], EntityEnderman['Enderman'/764651, l='MpServer', x=-63.16, y=64.00, z=-50.44], EntityEnderman['Enderman'/764642, l='MpServer', x=-15.07, y=63.00, z=-17.34], EntityEnderman['Enderman'/764667, l='MpServer', x=-72.66, y=60.00, z=10.53], EntityDragon['Ender Dragon'/734720, l='MpServer', x=-28.90, y=92.28, z=-7.32], EntityEnderman['Enderman'/764669, l='MpServer', x=-66.50, y=60.00, z=13.09], EntityEnderman['Enderman'/764657, l='MpServer', x=-60.53, y=62.00, z=-50.44], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/776490, l='MpServer', x=-54.50, y=66.00, z=-11.50], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/722266, l='MpServer', x=39.50, y=62.00, z=-39.50], EntityEnderman['Enderman'/764569, l='MpServer', x=-84.53, y=58.00, z=-4.97], EntityEnderman['Enderman'/764564, l='MpServer', x=-82.97, y=58.00, z=-3.59], EntityEnderman['Enderman'/764567, l='MpServer', x=-85.47, y=58.00, z=-2.44], EntityBlockFallingObsidian['entity.HardcoreEnderExpansion.FallingObsidian.name'/722239, l='MpServer', x=41.13, y=60.00, z=-48.50], EntityXPOrb['Experience Orb'/785158, l='MpServer', x=96.75, y=57.25, z=67.75]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:384)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2436)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:902)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 178006032 bytes (169 MB) / 478150656 bytes (456 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 136525 (7645400 bytes; 7 MB) allocated, 5 (280 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.129.1047 Minecraft Forge 10.12.0.1047 5 mods loaded, 5 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.129.1047} [Forge Mod Loader](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.0.1047} [Minecraft Forge](forge-1.7.2-10.12.0.1047.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advancedgenetics{1.5} [Advanced Genetics](advancedgenetics-1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreEnderExpansion{1.5-BETA} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.2-Forge10.12.0.1047
    LWJGL: 2.9.0
    OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2202, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2603 (145768 bytes; 0 MB) allocated, 22 (1232 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

I'm really wishing for this issue to get solved soon because these two mods are my favorite mods to play with.

**Comment by websitenmaker12** [comment]
From what mod is the ender dragon?

**Comment by MinecraftBossKiller** [comment]
Hardcore Ender Expansion, it adds 2 new ender dragons, adds other ender bosses on new biomes, and adds floating islands. Also the skin scale names are not working with the Hardcore Ender Expansion mobs as well. The two dragons are the baby ender dragon and the angry ender dragon.
