### ISSUE TITLE
Nothing shown in Gui ( 1.7.2 )

### ISSUE THREAD

**Issue by MinecraftBossKiller** [websitenmaker12/Advanced-Genetics#77]
I open the gui in a machine like the combustion generator and I will put coal in there. I open the gui later on and nothing is shown in there, but when I click on the spot where i placed the coal, coal appears in my inventory. I am not sure if it is a rendering problem with minecraft or with your mod, so I am reporting this.

**Comment by websitenmaker12** [comment]
Which Advanced Genetics version do you use?

**Comment by MinecraftBossKiller** [comment]
the 1.7.2 version 1.5 for advanced genetics

**Comment by websitenmaker12** [comment]
Tried it. Probably and issue with other mods.
