### ISSUE TITLE
Attack of the B Team, Microscope...

### ISSUE THREAD

**Issue by Rhawen** [websitenmaker12/Advanced-Genetics#79]
I'm playing on an Attack of the B Team server, and I made all the machines and etc in advanced genetics to get started. Once I drew blood from a creature using a syringe, I click on the microscope to analyze it and it's supposed to take a little bit but literally nothing happens, the screen stays blank like I'm not holding the centrifuged syringe?

**Comment by websitenmaker12** [comment]
At the moment, mobs didn't have their abilities in their blood.
