### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#8]
Scraper recipe conflict with "Ars Magicka 2" and "Atomic Science"

**Comment by websitenmaker12** [comment]
Make sure that this is not a ID-Conflict.

**Comment by InSimpleTermsJordan** [comment]
For those of you who also have this problem, DON'T set the IDs any higher than 31743 (for technical reasons, Forge can't use IDs above 31999 (Forge offsets IDs by 256 for whatever reason)). I suggest setting the highest IDs on the config of one of the conflicting mods to an ID LOWER than the lowest value on the same config before any edits. That's what worked for me.
