### ISSUE TITLE
Genetic Abilities disable player hitbox?

### ISSUE THREAD

**Issue by Vaygrim** [websitenmaker12/Advanced-Genetics#82]
MC 1.6.4 / Forge 965
Advanced Genetics 1.4.1 (in the Resonant Rise pack)

So I have quite the list of genetic abilities acquired and in use: Wooly, Lava Swimmer, Fly, Resistance, Water Breathing and More Hearts. Somewhere in the process of acquiring all of these abilities.. my player hit box has been disabled. Falling Anvils don't hurt me. I won't suffocate or take damage from falling gravel or sand. Even other players cannot effect me, seeing no hit box around me at all. Even Waila doesn't show a status box for me (indicating my name and health) when aimed at me.

I'm not quite sure which ability is causing it but I do know that my Sync Clone (which has none of my genetic abilities) does not have this issue, even if myself and the clone are both completely without equipment / gear of any kind.

This is far from critical as it isn't causing any crashes, however I do see it as breaking certain core mechanics with Minecraft itself.

Any thoughts? Let me know what other details you need from me, if any. Thanks!

**Comment by websitenmaker12** [comment]
That is wired. I am 100% sure that I am not changing the HitBox (also BoundingBox) of an entity in Advanced Genetics. Are you sure that this isn't caused by other mods?

**Comment by Vaygrim** [comment]
Well this is with the Resonant Rise modpack, which is chocked full of things that could complicate the issue, yes. However this issue persists even if I don't have my gear on. The only thing that can harm me in NPC monsters. Wands from Thuamcraft do nothing to me, lava does nothing to me, falling / gravity blocks and drowning does nothing to me.

So I've gone back through and checked what abilities I have currently in my bloodstream:
-More Hearts
-Resistance
-Flying
-Lava Swimmer
-Water Breathing
-Shoot Fireballs
-No-Fall
-Infinite Milk

There are several other players that are currently using Advanced Genetics, however they only use More Hearts and Resistance, with one using the Creeper "Explode" ability. Beyond that, I am the only person on the server with Lava Swimmer, Water Breathing, and Flying.

The issue that makes this complicated might be the fact that I am also using Advanced Genetics in combination with Sync, and I've managed to bug myself out in the process. I've used all my clones up, even used /kill after that to make sure. I can hug a cactus and take no damage, other players cannot hit me even on a server with PvP turned on.

Let me know what I need to do in order to test this, and I'll get the results to you right away.

**Comment by websitenmaker12** [comment]
I am sorry but I can't even imagine where a bug like this could be in Advanced Genetics.

**Comment by OldDogy** [comment]
I can confirm this, tho it;s in 1.4.3 and I only added flying. Nothing can hurt me i can't break blocks tho i can hit mobs..
What i notice is happening is that basically if i hold left-click on a grass it constantly breaks and repairs like that i'm hitting it (pressing and releasing leftclick) so fast that it dosen't even break so it comes back... ( like every item grass has durability for breaking and 1 leftclick has a certain "power" of hit, when i added Flying mutation that hit switched to 0)

**Comment by websitenmaker12** [comment]
I tested it but I never got this issue. What mods or which modpack are you playing?

**Comment by Vaygrim** [comment]
I have had this happen to me TWICE, once using the Resonant Rise pack and once using the Yogscast Complete Pack. I have tried several times to reproduce it but it always seems to be an extremely random 'freak event'. Not exactly sure what causes it.

**Comment by websitenmaker12** [comment]
Because of the fact that it is really hard to reproduce this issue I am not sure whether it is an issue of Advanced Genetics or annother mod.

**Comment by Vaygrim** [comment]
Both times this has happened to me, the only way I could get it resolved was to either remove the abilities via Anti-Serum (then everything went back to normal).. or have the Advanced Genetics abilities manually removed from my player.dat via editing.
