### ISSUE TITLE
Can't acalyze Skin Scales

### ISSUE THREAD

**Issue by kruuse** [websitenmaker12/Advanced-Genetics#84]
Hello, I can't analyze skin scales. I've installed forge for 1.7.2. I've put mod in modfolder, but it won't work. Arrow doesn't move and I've tried to wait anyway, but nothing happens. I've also tried download the mod once again, but it didn't help.

![image](https://cloud.githubusercontent.com/assets/7352422/2750440/b7183eca-c879-11e3-8a13-367a704c0f5f.png)

**Comment by websitenmaker12** [comment]
You need power. Take a look at the wiki.

**Comment by kruuse** [comment]
Thank you, Now I found the wiki, that will help a lot.
