### ISSUE TITLE
[Urgent] Heavy network issues with bungeecord

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#90]
We migrated to bungeecord, and that's what the OPIS said:
http://puu.sh/8vkXI.png

Is there any kind of loop?

**Comment by websitenmaker12** [comment]
Which version of Advanced Genetics do you use?

**Comment by ghost** [comment]
We're using v1.4.1 in the current FTB Monster 1.1.1 pack.

**Comment by websitenmaker12** [comment]
This is the problem. http://ag.teamdna.de/sites/changelog.php?v=r1.4.2&t=1 Thats the changelog of the last update which fixes this.
