### ISSUE TITLE
power in 1.7.2

### ISSUE THREAD

**Issue by h2ohard** [websitenmaker12/Advanced-Genetics#91]
it may not be a bug, i'm playing the FTB 1.7.2 unstable version, and i'm not saying anything is wrong. but they removed IC2 and thermal ex is not in the pack yet, the only way to power the machines is burning things is the genny you provide, my problem is that it eats so much to run the machines ( i went through 40 stacks of charcoal ) do get one gene done, is this right? also there is Ender IO in the pack that alows for RF power, but the machines and cable won't connect, is this going to be fixed or working as intended?

**Comment by websitenmaker12** [comment]
Yes, I know that it costs a lot of material but this was done on purpose. If you don't like it, you can
change the amount of energy that a machine uses in the Advanced Genetics config.
