### ISSUE TITLE
Storing/Sorting AG items

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [websitenmaker12/Advanced-Genetics#92]
I started, after some time, to have problems with the amount of mob scales, helixes and genes.

When I try to store them in a ME network or archive, none of them would stack and, even worse, I can't sort them in any way, since their name is the same (we just know their type by their description).

Being impossible to sort and store them for future players/friends I get completely lost working with the amount of scales, helixes and genes that I've acquired.

A suggestion (which doesn't seem to be easy to do) is to change the items are named and their IDs/Metadata. This way they'll be easily sorted and stored by a lot of other mods (in the worst case, create a machine that would be a freezer to store all that, sort and search).

Sorry for my poor English,
Thank you ; )

**Comment by websitenmaker12** [comment]
Hi. I know that this annoys but to change it I must rewrite Advanced Genetics because the problem is that each of that items have different NBT Datas. I am sorry but there is no other way than store the items in chests.
