### ISSUE TITLE
AdvGenetics v1.5.2 MCPC-Plus Server Crash

### ISSUE THREAD

**Issue by BlackYamato** [websitenmaker12/Advanced-Genetics#94]
---- Environment ---
・Minecraft 1.7.2
・Minecraft Forge 10.12.1.1065
・MCPC-Plus 1.7.2 R0.4 B68
・Advanced Genetics 1.5.2
・Industrial Craft 2.1.477

---- Minecraft Server Crash Report ---
・http://pastebin.com/PDp8W0tH
・http://pastebin.com/yZ4dUdaS
・http://pastebin.com/vFi6QKuh

**Comment by websitenmaker12** [comment]
Can you please explain what you did before the game crashes?
