### ISSUE TITLE
Bug with the infinite milk gene

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#95]
when you use a bucket to get milk from a infinite milk gene mob,will make a normal milk,along with a ghost iron shovel,and plus,you cant get milk from that gene mob in creative mod

~~ JohnHOne/joaoh1

**Comment by websitenmaker12** [comment]
Do you have other mods installed?

**Comment by ghost** [comment]
no,i'm with the advanced genetics 1.5.2 only

**Comment by websitenmaker12** [comment]
I'll test it.

**Comment by ghost** [comment]
you forgot this issue

**Comment by websitenmaker12** [comment]
No, I didn't but I have less time atm and this isn't a that important issue.

**Comment by websitenmaker12** [comment]
Is fixed in the next update.
