### ISSUE TITLE
burning up in lava

### ISSUE THREAD

**Issue by k-mtar** [websitenmaker12/Advanced-Genetics#96]
hi 

i've been playing attack of the b-taem and have been exploring your mod, i;ve just created the "swim in lava" gene and used it upon myself, the trouble is i still burn when i stand in lava which as you can probably guess stops me from doing the swimming part of the genes description. 
is there a possibility the gene failed to take ? or is this a bug ?

**Comment by websitenmaker12** [comment]
Hi.
This isn't a bug. It is one of the core "features" of Advanced Genetics. AG2 won't have it anymore.
