### ISSUE TITLE
Canupdate true with no updateentity override

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#97]
On my (private) server's start up, i get the following messages:
- Detected TE com.advGenetics.TileEntity.TileEntityMicroscope with canUpdate set to true and no updateEntity override!.

Can this be fixed? I'm doing a sweep over mods that give me the message.

Thanks in advance,
dust6161

**Comment by ghost** [comment]
When Modjam 4 Ends,the owners will check the post
Thank you

**Comment by websitenmaker12** [comment]
Should be fixed.
