### ISSUE TITLE
Overclockers cause an infinite power drain.

### ISSUE THREAD

**Issue by Donutfreak** [websitenmaker12/Advanced-Genetics#99]
When using 16 overclockers in a machine, it will drain the internal power reserves of the machine quickly enough that it will not be able to complete a cycle. It still uses energy but the cycle doesn't complete.

For instance the internal buffer on the auto splitter doesn't have enough energy to turn a Helix into a Gene, but it will still try to. This happens over and over without stopping, continually wasting energy.

My theory is that the amount of power required is higher than the power threshold in which the conversion process is started.

I've tried 4000RF/t input on a machine, but the buffer doesn't recharge quickly enough to allow continuous operation with 16 overclockers.

My apologies if this has been addressed or if I'm doing something wrong here. Tested on 1.6.4 FTB Monster pack.

![2014-05-19_14 31 01](https://cloud.githubusercontent.com/assets/3360326/3020292/0f58293a-df9d-11e3-8670-8408e2ef799d.png)

**Comment by websitenmaker12** [comment]
Which Advanced Genetics version is it?

**Comment by Donutfreak** [comment]
My bad, I thought the FTB version would be enough information.

It's version 1.4.1. I don't know why I didn't check to see that V1.4.2 is the latest for MC 1.6.4. Thank you for replying so quickly. I'll assume this is actually fixed in the most recent version. 

Somehow I assumed the FTB would have the latest version for 1.6.4 in their Monster pack. I guess everyone is probably focused on the Unstable 1.7.2(v1.0.3) FTB pack. Seriously though, thanks for the speedy response. Much appreciated.
